// clang-format off
// @NOTE: order of includes is important here
#include <openvr_driver.h>
#include "log_formatters.h"
#include <fmt/chrono.h>
// clang-format on

auto fmtquill::formatter<ipc::protocol::Version_t>::format(ipc::protocol::Version_t version, format_context& ctx) const -> format_context::iterator
{
    string_view versionStr {};
    switch (version) {
    case ipc::protocol::IPC_PROTOCOL_VER_INVALID:
        versionStr = "IPC_PROTOCOL_VER_INVALID";
        break;
    case ipc::protocol::IPC_PROTOCOL_VER_1:
        versionStr = "IPC_PROTOCOL_VER_1";
        break;
    case ipc::protocol::IPC_PROTOCOL_VER_2:
        versionStr = "IPC_PROTOCOL_VER_2";
        break;
    case ipc::protocol::IPC_PROTOCOL_VER_3:
        versionStr = "IPC_PROTOCOL_VER_3";
        break;
    case ipc::protocol::IPC_PROTOCOL_VER_4:
        versionStr = "IPC_PROTOCOL_VER_4";
        break;
    case ipc::protocol::IPC_PROTOCOL_VER_5:
        versionStr = "IPC_PROTOCOL_VER_5";
        break;
    default:
        versionStr = fmtquill::format("IPC_PROTOCOL_VER_UNK_", (uint32_t)version);
        break;
    }
    return formatter<string_view>::format(versionStr, ctx);
}

namespace vr {
std::string format_as(EVROverlayError overlayErr)
{
    switch (overlayErr) {
    case EVROverlayError::VROverlayError_None:
        return "VROverlayError_None";
    case EVROverlayError::VROverlayError_UnknownOverlay:
        return "VROverlayError_UnknownOverlay";
    case EVROverlayError::VROverlayError_InvalidHandle:
        return "VROverlayError_InvalidHandle";
    case EVROverlayError::VROverlayError_PermissionDenied:
        return "VROverlayError_PermissionDenied";
    case EVROverlayError::VROverlayError_OverlayLimitExceeded:
        return "VROverlayError_OverlayLimitExceeded";
    case EVROverlayError::VROverlayError_WrongVisibilityType:
        return "VROverlayError_WrongVisibilityType";
    case EVROverlayError::VROverlayError_KeyTooLong:
        return "VROverlayError_KeyTooLong";
    case EVROverlayError::VROverlayError_NameTooLong:
        return "VROverlayError_NameTooLong";
    case EVROverlayError::VROverlayError_KeyInUse:
        return "VROverlayError_KeyInUse";
    case EVROverlayError::VROverlayError_WrongTransformType:
        return "VROverlayError_WrongTransformType";
    case EVROverlayError::VROverlayError_InvalidTrackedDevice:
        return "VROverlayError_InvalidTrackedDevice";
    case EVROverlayError::VROverlayError_InvalidParameter:
        return "VROverlayError_InvalidParameter";
    case EVROverlayError::VROverlayError_ThumbnailCantBeDestroyed:
        return "VROverlayError_ThumbnailCantBeDestroyed";
    case EVROverlayError::VROverlayError_ArrayTooSmall:
        return "VROverlayError_ArrayTooSmall";
    case EVROverlayError::VROverlayError_RequestFailed:
        return "VROverlayError_RequestFailed";
    case EVROverlayError::VROverlayError_InvalidTexture:
        return "VROverlayError_InvalidTexture";
    case EVROverlayError::VROverlayError_UnableToLoadFile:
        return "VROverlayError_UnableToLoadFile";
    case EVROverlayError::VROverlayError_KeyboardAlreadyInUse:
        return "VROverlayError_KeyboardAlreadyInUse";
    case EVROverlayError::VROverlayError_NoNeighbor:
        return "VROverlayError_NoNeighbor";
    case EVROverlayError::VROverlayError_TooManyMaskPrimitives:
        return "VROverlayError_TooManyMaskPrimitives";
    case EVROverlayError::VROverlayError_BadMaskPrimitive:
        return "VROverlayError_BadMaskPrimitive";
    case EVROverlayError::VROverlayError_TextureAlreadyLocked:
        return "VROverlayError_TextureAlreadyLocked";
    case EVROverlayError::VROverlayError_TextureLockCapacityReached:
        return "VROverlayError_TextureLockCapacityReached";
    case EVROverlayError::VROverlayError_TextureNotLocked:
        return "VROverlayError_TextureNotLocked";
    case EVROverlayError::VROverlayError_TimedOut:
        return "VROverlayError_TimedOut";
    default:
        return fmt::format("VROverlayError_{}", (uint32_t)overlayErr);
    }
}

std::string format_as(EVRInitError initErr)
{
    switch (initErr) {
    case EVRInitError::VRInitError_None:
        return "VRInitError_None";
    case EVRInitError::VRInitError_Unknown:
        return "VRInitError_Unknown";
    case EVRInitError::VRInitError_Init_InstallationNotFound:
        return "VRInitError_Init_InstallationNotFound";
    case EVRInitError::VRInitError_Init_InstallationCorrupt:
        return "VRInitError_Init_InstallationCorrupt";
    case EVRInitError::VRInitError_Init_VRClientDLLNotFound:
        return "VRInitError_Init_VRClientDLLNotFound";
    case EVRInitError::VRInitError_Init_FileNotFound:
        return "VRInitError_Init_FileNotFound";
    case EVRInitError::VRInitError_Init_FactoryNotFound:
        return "VRInitError_Init_FactoryNotFound";
    case EVRInitError::VRInitError_Init_InterfaceNotFound:
        return "VRInitError_Init_InterfaceNotFound";
    case EVRInitError::VRInitError_Init_InvalidInterface:
        return "VRInitError_Init_InvalidInterface";
    case EVRInitError::VRInitError_Init_UserConfigDirectoryInvalid:
        return "VRInitError_Init_UserConfigDirectoryInvalid";
    case EVRInitError::VRInitError_Init_HmdNotFound:
        return "VRInitError_Init_HmdNotFound";
    case EVRInitError::VRInitError_Init_NotInitialized:
        return "VRInitError_Init_NotInitialized";
    case EVRInitError::VRInitError_Init_PathRegistryNotFound:
        return "VRInitError_Init_PathRegistryNotFound";
    case EVRInitError::VRInitError_Init_NoConfigPath:
        return "VRInitError_Init_NoConfigPath";
    case EVRInitError::VRInitError_Init_NoLogPath:
        return "VRInitError_Init_NoLogPath";
    case EVRInitError::VRInitError_Init_PathRegistryNotWritable:
        return "VRInitError_Init_PathRegistryNotWritable";
    case EVRInitError::VRInitError_Init_AppInfoInitFailed:
        return "VRInitError_Init_AppInfoInitFailed";
    case EVRInitError::VRInitError_Init_Retry:
        return "VRInitError_Init_Retry";
    case EVRInitError::VRInitError_Init_InitCanceledByUser:
        return "VRInitError_Init_InitCanceledByUser";
    case EVRInitError::VRInitError_Init_AnotherAppLaunching:
        return "VRInitError_Init_AnotherAppLaunching";
    case EVRInitError::VRInitError_Init_SettingsInitFailed:
        return "VRInitError_Init_SettingsInitFailed";
    case EVRInitError::VRInitError_Init_ShuttingDown:
        return "VRInitError_Init_ShuttingDown";
    case EVRInitError::VRInitError_Init_TooManyObjects:
        return "VRInitError_Init_TooManyObjects";
    case EVRInitError::VRInitError_Init_NoServerForBackgroundApp:
        return "VRInitError_Init_NoServerForBackgroundApp";
    case EVRInitError::VRInitError_Init_NotSupportedWithCompositor:
        return "VRInitError_Init_NotSupportedWithCompositor";
    case EVRInitError::VRInitError_Init_NotAvailableToUtilityApps:
        return "VRInitError_Init_NotAvailableToUtilityApps";
    case EVRInitError::VRInitError_Init_Internal:
        return "VRInitError_Init_Internal";
    case EVRInitError::VRInitError_Init_HmdDriverIdIsNone:
        return "VRInitError_Init_HmdDriverIdIsNone";
    case EVRInitError::VRInitError_Init_HmdNotFoundPresenceFailed:
        return "VRInitError_Init_HmdNotFoundPresenceFailed";
    case EVRInitError::VRInitError_Init_VRMonitorNotFound:
        return "VRInitError_Init_VRMonitorNotFound";
    case EVRInitError::VRInitError_Init_VRMonitorStartupFailed:
        return "VRInitError_Init_VRMonitorStartupFailed";
    case EVRInitError::VRInitError_Init_LowPowerWatchdogNotSupported:
        return "VRInitError_Init_LowPowerWatchdogNotSupported";
    case EVRInitError::VRInitError_Init_InvalidApplicationType:
        return "VRInitError_Init_InvalidApplicationType";
    case EVRInitError::VRInitError_Init_NotAvailableToWatchdogApps:
        return "VRInitError_Init_NotAvailableToWatchdogApps";
    case EVRInitError::VRInitError_Init_WatchdogDisabledInSettings:
        return "VRInitError_Init_WatchdogDisabledInSettings";
    case EVRInitError::VRInitError_Init_VRDashboardNotFound:
        return "VRInitError_Init_VRDashboardNotFound";
    case EVRInitError::VRInitError_Init_VRDashboardStartupFailed:
        return "VRInitError_Init_VRDashboardStartupFailed";
    case EVRInitError::VRInitError_Init_VRHomeNotFound:
        return "VRInitError_Init_VRHomeNotFound";
    case EVRInitError::VRInitError_Init_VRHomeStartupFailed:
        return "VRInitError_Init_VRHomeStartupFailed";
    case EVRInitError::VRInitError_Init_RebootingBusy:
        return "VRInitError_Init_RebootingBusy";
    case EVRInitError::VRInitError_Init_FirmwareUpdateBusy:
        return "VRInitError_Init_FirmwareUpdateBusy";
    case EVRInitError::VRInitError_Init_FirmwareRecoveryBusy:
        return "VRInitError_Init_FirmwareRecoveryBusy";
    case EVRInitError::VRInitError_Init_USBServiceBusy:
        return "VRInitError_Init_USBServiceBusy";
    case EVRInitError::VRInitError_Init_VRWebHelperStartupFailed:
        return "VRInitError_Init_VRWebHelperStartupFailed";
    case EVRInitError::VRInitError_Init_TrackerManagerInitFailed:
        return "VRInitError_Init_TrackerManagerInitFailed";
    case EVRInitError::VRInitError_Init_AlreadyRunning:
        return "VRInitError_Init_AlreadyRunning";
    case EVRInitError::VRInitError_Init_FailedForVrMonitor:
        return "VRInitError_Init_FailedForVrMonitor";
    case EVRInitError::VRInitError_Init_PropertyManagerInitFailed:
        return "VRInitError_Init_PropertyManagerInitFailed";
    case EVRInitError::VRInitError_Init_WebServerFailed:
        return "VRInitError_Init_WebServerFailed";
    case EVRInitError::VRInitError_Init_IllegalTypeTransition:
        return "VRInitError_Init_IllegalTypeTransition";
    case EVRInitError::VRInitError_Init_MismatchedRuntimes:
        return "VRInitError_Init_MismatchedRuntimes";
    case EVRInitError::VRInitError_Init_InvalidProcessId:
        return "VRInitError_Init_InvalidProcessId";
    case EVRInitError::VRInitError_Init_VRServiceStartupFailed:
        return "VRInitError_Init_VRServiceStartupFailed";
    case EVRInitError::VRInitError_Init_PrismNeedsNewDrivers:
        return "VRInitError_Init_PrismNeedsNewDrivers";
    case EVRInitError::VRInitError_Init_PrismStartupTimedOut:
        return "VRInitError_Init_PrismStartupTimedOut";
    case EVRInitError::VRInitError_Init_CouldNotStartPrism:
        return "VRInitError_Init_CouldNotStartPrism";
    case EVRInitError::VRInitError_Init_PrismClientInitFailed:
        return "VRInitError_Init_PrismClientInitFailed";
    case EVRInitError::VRInitError_Init_PrismClientStartFailed:
        return "VRInitError_Init_PrismClientStartFailed";
    case EVRInitError::VRInitError_Init_PrismExitedUnexpectedly:
        return "VRInitError_Init_PrismExitedUnexpectedly";
    case EVRInitError::VRInitError_Init_BadLuid:
        return "VRInitError_Init_BadLuid";
    case EVRInitError::VRInitError_Init_NoServerForAppContainer:
        return "VRInitError_Init_NoServerForAppContainer";
    case EVRInitError::VRInitError_Init_DuplicateBootstrapper:
        return "VRInitError_Init_DuplicateBootstrapper";
    case EVRInitError::VRInitError_Init_VRDashboardServicePending:
        return "VRInitError_Init_VRDashboardServicePending";
    case EVRInitError::VRInitError_Init_VRDashboardServiceTimeout:
        return "VRInitError_Init_VRDashboardServiceTimeout";
    case EVRInitError::VRInitError_Init_VRDashboardServiceStopped:
        return "VRInitError_Init_VRDashboardServiceStopped";
    case EVRInitError::VRInitError_Init_VRDashboardAlreadyStarted:
        return "VRInitError_Init_VRDashboardAlreadyStarted";
    case EVRInitError::VRInitError_Init_VRDashboardCopyFailed:
        return "VRInitError_Init_VRDashboardCopyFailed";
    case EVRInitError::VRInitError_Init_VRDashboardTokenFailure:
        return "VRInitError_Init_VRDashboardTokenFailure";
    case EVRInitError::VRInitError_Init_VRDashboardEnvironmentFailure:
        return "VRInitError_Init_VRDashboardEnvironmentFailure";
    case EVRInitError::VRInitError_Init_VRDashboardPathFailure:
        return "VRInitError_Init_VRDashboardPathFailure";
    case EVRInitError::VRInitError_Driver_Failed:
        return "VRInitError_Driver_Failed";
    case EVRInitError::VRInitError_Driver_Unknown:
        return "VRInitError_Driver_Unknown";
    case EVRInitError::VRInitError_Driver_HmdUnknown:
        return "VRInitError_Driver_HmdUnknown";
    case EVRInitError::VRInitError_Driver_NotLoaded:
        return "VRInitError_Driver_NotLoaded";
    case EVRInitError::VRInitError_Driver_RuntimeOutOfDate:
        return "VRInitError_Driver_RuntimeOutOfDate";
    case EVRInitError::VRInitError_Driver_HmdInUse:
        return "VRInitError_Driver_HmdInUse";
    case EVRInitError::VRInitError_Driver_NotCalibrated:
        return "VRInitError_Driver_NotCalibrated";
    case EVRInitError::VRInitError_Driver_CalibrationInvalid:
        return "VRInitError_Driver_CalibrationInvalid";
    case EVRInitError::VRInitError_Driver_HmdDisplayNotFound:
        return "VRInitError_Driver_HmdDisplayNotFound";
    case EVRInitError::VRInitError_Driver_TrackedDeviceInterfaceUnknown:
        return "VRInitError_Driver_TrackedDeviceInterfaceUnknown";
    case EVRInitError::VRInitError_Driver_HmdDriverIdOutOfBounds:
        return "VRInitError_Driver_HmdDriverIdOutOfBounds";
    case EVRInitError::VRInitError_Driver_HmdDisplayMirrored:
        return "VRInitError_Driver_HmdDisplayMirrored";
    case EVRInitError::VRInitError_Driver_HmdDisplayNotFoundLaptop:
        return "VRInitError_Driver_HmdDisplayNotFoundLaptop";
    case EVRInitError::VRInitError_Driver_PeerDriverNotInstalled:
        return "VRInitError_Driver_PeerDriverNotInstalled";
    case EVRInitError::VRInitError_Driver_WirelessHmdNotConnected:
        return "VRInitError_Driver_WirelessHmdNotConnected";
    case EVRInitError::VRInitError_IPC_ServerInitFailed:
        return "VRInitError_IPC_ServerInitFailed";
    case EVRInitError::VRInitError_IPC_ConnectFailed:
        return "VRInitError_IPC_ConnectFailed";
    case EVRInitError::VRInitError_IPC_SharedStateInitFailed:
        return "VRInitError_IPC_SharedStateInitFailed";
    case EVRInitError::VRInitError_IPC_CompositorInitFailed:
        return "VRInitError_IPC_CompositorInitFailed";
    case EVRInitError::VRInitError_IPC_MutexInitFailed:
        return "VRInitError_IPC_MutexInitFailed";
    case EVRInitError::VRInitError_IPC_Failed:
        return "VRInitError_IPC_Failed";
    case EVRInitError::VRInitError_IPC_CompositorConnectFailed:
        return "VRInitError_IPC_CompositorConnectFailed";
    case EVRInitError::VRInitError_IPC_CompositorInvalidConnectResponse:
        return "VRInitError_IPC_CompositorInvalidConnectResponse";
    case EVRInitError::VRInitError_IPC_ConnectFailedAfterMultipleAttempts:
        return "VRInitError_IPC_ConnectFailedAfterMultipleAttempts";
    case EVRInitError::VRInitError_IPC_ConnectFailedAfterTargetExited:
        return "VRInitError_IPC_ConnectFailedAfterTargetExited";
    case EVRInitError::VRInitError_IPC_NamespaceUnavailable:
        return "VRInitError_IPC_NamespaceUnavailable";
    case EVRInitError::VRInitError_Compositor_Failed:
        return "VRInitError_Compositor_Failed";
    case EVRInitError::VRInitError_Compositor_D3D11HardwareRequired:
        return "VRInitError_Compositor_D3D11HardwareRequired";
    case EVRInitError::VRInitError_Compositor_FirmwareRequiresUpdate:
        return "VRInitError_Compositor_FirmwareRequiresUpdate";
    case EVRInitError::VRInitError_Compositor_OverlayInitFailed:
        return "VRInitError_Compositor_OverlayInitFailed";
    case EVRInitError::VRInitError_Compositor_ScreenshotsInitFailed:
        return "VRInitError_Compositor_ScreenshotsInitFailed";
    case EVRInitError::VRInitError_Compositor_UnableToCreateDevice:
        return "VRInitError_Compositor_UnableToCreateDevice";
    case EVRInitError::VRInitError_Compositor_SharedStateIsNull:
        return "VRInitError_Compositor_SharedStateIsNull";
    case EVRInitError::VRInitError_Compositor_NotificationManagerIsNull:
        return "VRInitError_Compositor_NotificationManagerIsNull";
    case EVRInitError::VRInitError_Compositor_ResourceManagerClientIsNull:
        return "VRInitError_Compositor_ResourceManagerClientIsNull";
    case EVRInitError::VRInitError_Compositor_MessageOverlaySharedStateInitFailure:
        return "VRInitError_Compositor_MessageOverlaySharedStateInitFailure";
    case EVRInitError::VRInitError_Compositor_PropertiesInterfaceIsNull:
        return "VRInitError_Compositor_PropertiesInterfaceIsNull";
    case EVRInitError::VRInitError_Compositor_CreateFullscreenWindowFailed:
        return "VRInitError_Compositor_CreateFullscreenWindowFailed";
    case EVRInitError::VRInitError_Compositor_SettingsInterfaceIsNull:
        return "VRInitError_Compositor_SettingsInterfaceIsNull";
    case EVRInitError::VRInitError_Compositor_FailedToShowWindow:
        return "VRInitError_Compositor_FailedToShowWindow";
    case EVRInitError::VRInitError_Compositor_DistortInterfaceIsNull:
        return "VRInitError_Compositor_DistortInterfaceIsNull";
    case EVRInitError::VRInitError_Compositor_DisplayFrequencyFailure:
        return "VRInitError_Compositor_DisplayFrequencyFailure";
    case EVRInitError::VRInitError_Compositor_RendererInitializationFailed:
        return "VRInitError_Compositor_RendererInitializationFailed";
    case EVRInitError::VRInitError_Compositor_DXGIFactoryInterfaceIsNull:
        return "VRInitError_Compositor_DXGIFactoryInterfaceIsNull";
    case EVRInitError::VRInitError_Compositor_DXGIFactoryCreateFailed:
        return "VRInitError_Compositor_DXGIFactoryCreateFailed";
    case EVRInitError::VRInitError_Compositor_DXGIFactoryQueryFailed:
        return "VRInitError_Compositor_DXGIFactoryQueryFailed";
    case EVRInitError::VRInitError_Compositor_InvalidAdapterDesktop:
        return "VRInitError_Compositor_InvalidAdapterDesktop";
    case EVRInitError::VRInitError_Compositor_InvalidHmdAttachment:
        return "VRInitError_Compositor_InvalidHmdAttachment";
    case EVRInitError::VRInitError_Compositor_InvalidOutputDesktop:
        return "VRInitError_Compositor_InvalidOutputDesktop";
    case EVRInitError::VRInitError_Compositor_InvalidDeviceProvided:
        return "VRInitError_Compositor_InvalidDeviceProvided";
    case EVRInitError::VRInitError_Compositor_D3D11RendererInitializationFailed:
        return "VRInitError_Compositor_D3D11RendererInitializationFailed";
    case EVRInitError::VRInitError_Compositor_FailedToFindDisplayMode:
        return "VRInitError_Compositor_FailedToFindDisplayMode";
    case EVRInitError::VRInitError_Compositor_FailedToCreateSwapChain:
        return "VRInitError_Compositor_FailedToCreateSwapChain";
    case EVRInitError::VRInitError_Compositor_FailedToGetBackBuffer:
        return "VRInitError_Compositor_FailedToGetBackBuffer";
    case EVRInitError::VRInitError_Compositor_FailedToCreateRenderTarget:
        return "VRInitError_Compositor_FailedToCreateRenderTarget";
    case EVRInitError::VRInitError_Compositor_FailedToCreateDXGI2SwapChain:
        return "VRInitError_Compositor_FailedToCreateDXGI2SwapChain";
    case EVRInitError::VRInitError_Compositor_FailedtoGetDXGI2BackBuffer:
        return "VRInitError_Compositor_FailedtoGetDXGI2BackBuffer";
    case EVRInitError::VRInitError_Compositor_FailedToCreateDXGI2RenderTarget:
        return "VRInitError_Compositor_FailedToCreateDXGI2RenderTarget";
    case EVRInitError::VRInitError_Compositor_FailedToGetDXGIDeviceInterface:
        return "VRInitError_Compositor_FailedToGetDXGIDeviceInterface";
    case EVRInitError::VRInitError_Compositor_SelectDisplayMode:
        return "VRInitError_Compositor_SelectDisplayMode";
    case EVRInitError::VRInitError_Compositor_FailedToCreateNvAPIRenderTargets:
        return "VRInitError_Compositor_FailedToCreateNvAPIRenderTargets";
    case EVRInitError::VRInitError_Compositor_NvAPISetDisplayMode:
        return "VRInitError_Compositor_NvAPISetDisplayMode";
    case EVRInitError::VRInitError_Compositor_FailedToCreateDirectModeDisplay:
        return "VRInitError_Compositor_FailedToCreateDirectModeDisplay";
    case EVRInitError::VRInitError_Compositor_InvalidHmdPropertyContainer:
        return "VRInitError_Compositor_InvalidHmdPropertyContainer";
    case EVRInitError::VRInitError_Compositor_UpdateDisplayFrequency:
        return "VRInitError_Compositor_UpdateDisplayFrequency";
    case EVRInitError::VRInitError_Compositor_CreateRasterizerState:
        return "VRInitError_Compositor_CreateRasterizerState";
    case EVRInitError::VRInitError_Compositor_CreateWireframeRasterizerState:
        return "VRInitError_Compositor_CreateWireframeRasterizerState";
    case EVRInitError::VRInitError_Compositor_CreateSamplerState:
        return "VRInitError_Compositor_CreateSamplerState";
    case EVRInitError::VRInitError_Compositor_CreateClampToBorderSamplerState:
        return "VRInitError_Compositor_CreateClampToBorderSamplerState";
    case EVRInitError::VRInitError_Compositor_CreateAnisoSamplerState:
        return "VRInitError_Compositor_CreateAnisoSamplerState";
    case EVRInitError::VRInitError_Compositor_CreateOverlaySamplerState:
        return "VRInitError_Compositor_CreateOverlaySamplerState";
    case EVRInitError::VRInitError_Compositor_CreatePanoramaSamplerState:
        return "VRInitError_Compositor_CreatePanoramaSamplerState";
    case EVRInitError::VRInitError_Compositor_CreateFontSamplerState:
        return "VRInitError_Compositor_CreateFontSamplerState";
    case EVRInitError::VRInitError_Compositor_CreateNoBlendState:
        return "VRInitError_Compositor_CreateNoBlendState";
    case EVRInitError::VRInitError_Compositor_CreateBlendState:
        return "VRInitError_Compositor_CreateBlendState";
    case EVRInitError::VRInitError_Compositor_CreateAlphaBlendState:
        return "VRInitError_Compositor_CreateAlphaBlendState";
    case EVRInitError::VRInitError_Compositor_CreateBlendStateMaskR:
        return "VRInitError_Compositor_CreateBlendStateMaskR";
    case EVRInitError::VRInitError_Compositor_CreateBlendStateMaskG:
        return "VRInitError_Compositor_CreateBlendStateMaskG";
    case EVRInitError::VRInitError_Compositor_CreateBlendStateMaskB:
        return "VRInitError_Compositor_CreateBlendStateMaskB";
    case EVRInitError::VRInitError_Compositor_CreateDepthStencilState:
        return "VRInitError_Compositor_CreateDepthStencilState";
    case EVRInitError::VRInitError_Compositor_CreateDepthStencilStateNoWrite:
        return "VRInitError_Compositor_CreateDepthStencilStateNoWrite";
    case EVRInitError::VRInitError_Compositor_CreateDepthStencilStateNoDepth:
        return "VRInitError_Compositor_CreateDepthStencilStateNoDepth";
    case EVRInitError::VRInitError_Compositor_CreateFlushTexture:
        return "VRInitError_Compositor_CreateFlushTexture";
    case EVRInitError::VRInitError_Compositor_CreateDistortionSurfaces:
        return "VRInitError_Compositor_CreateDistortionSurfaces";
    case EVRInitError::VRInitError_Compositor_CreateConstantBuffer:
        return "VRInitError_Compositor_CreateConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateHmdPoseConstantBuffer:
        return "VRInitError_Compositor_CreateHmdPoseConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateHmdPoseStagingConstantBuffer:
        return "VRInitError_Compositor_CreateHmdPoseStagingConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateSharedFrameInfoConstantBuffer:
        return "VRInitError_Compositor_CreateSharedFrameInfoConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateOverlayConstantBuffer:
        return "VRInitError_Compositor_CreateOverlayConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateSceneTextureIndexConstantBuffer:
        return "VRInitError_Compositor_CreateSceneTextureIndexConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateReadableSceneTextureIndexConstantBuffer:
        return "VRInitError_Compositor_CreateReadableSceneTextureIndexConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateLayerGraphicsTextureIndexConstantBuffer:
        return "VRInitError_Compositor_CreateLayerGraphicsTextureIndexConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateLayerComputeTextureIndexConstantBuffer:
        return "VRInitError_Compositor_CreateLayerComputeTextureIndexConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateLayerComputeSceneTextureIndexConstantBuffer:
        return "VRInitError_Compositor_CreateLayerComputeSceneTextureIndexConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateComputeHmdPoseConstantBuffer:
        return "VRInitError_Compositor_CreateComputeHmdPoseConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreateGeomConstantBuffer:
        return "VRInitError_Compositor_CreateGeomConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreatePanelMaskConstantBuffer:
        return "VRInitError_Compositor_CreatePanelMaskConstantBuffer";
    case EVRInitError::VRInitError_Compositor_CreatePixelSimUBO:
        return "VRInitError_Compositor_CreatePixelSimUBO";
    case EVRInitError::VRInitError_Compositor_CreateMSAARenderTextures:
        return "VRInitError_Compositor_CreateMSAARenderTextures";
    case EVRInitError::VRInitError_Compositor_CreateResolveRenderTextures:
        return "VRInitError_Compositor_CreateResolveRenderTextures";
    case EVRInitError::VRInitError_Compositor_CreateComputeResolveRenderTextures:
        return "VRInitError_Compositor_CreateComputeResolveRenderTextures";
    case EVRInitError::VRInitError_Compositor_CreateDriverDirectModeResolveTextures:
        return "VRInitError_Compositor_CreateDriverDirectModeResolveTextures";
    case EVRInitError::VRInitError_Compositor_OpenDriverDirectModeResolveTextures:
        return "VRInitError_Compositor_OpenDriverDirectModeResolveTextures";
    case EVRInitError::VRInitError_Compositor_CreateFallbackSyncTexture:
        return "VRInitError_Compositor_CreateFallbackSyncTexture";
    case EVRInitError::VRInitError_Compositor_ShareFallbackSyncTexture:
        return "VRInitError_Compositor_ShareFallbackSyncTexture";
    case EVRInitError::VRInitError_Compositor_CreateOverlayIndexBuffer:
        return "VRInitError_Compositor_CreateOverlayIndexBuffer";
    case EVRInitError::VRInitError_Compositor_CreateOverlayVertexBuffer:
        return "VRInitError_Compositor_CreateOverlayVertexBuffer";
    case EVRInitError::VRInitError_Compositor_CreateTextVertexBuffer:
        return "VRInitError_Compositor_CreateTextVertexBuffer";
    case EVRInitError::VRInitError_Compositor_CreateTextIndexBuffer:
        return "VRInitError_Compositor_CreateTextIndexBuffer";
    case EVRInitError::VRInitError_Compositor_CreateMirrorTextures:
        return "VRInitError_Compositor_CreateMirrorTextures";
    case EVRInitError::VRInitError_Compositor_CreateLastFrameRenderTexture:
        return "VRInitError_Compositor_CreateLastFrameRenderTexture";
    case EVRInitError::VRInitError_Compositor_CreateMirrorOverlay:
        return "VRInitError_Compositor_CreateMirrorOverlay";
    case EVRInitError::VRInitError_Compositor_FailedToCreateVirtualDisplayBackbuffer:
        return "VRInitError_Compositor_FailedToCreateVirtualDisplayBackbuffer";
    case EVRInitError::VRInitError_Compositor_DisplayModeNotSupported:
        return "VRInitError_Compositor_DisplayModeNotSupported";
    case EVRInitError::VRInitError_Compositor_CreateOverlayInvalidCall:
        return "VRInitError_Compositor_CreateOverlayInvalidCall";
    case EVRInitError::VRInitError_Compositor_CreateOverlayAlreadyInitialized:
        return "VRInitError_Compositor_CreateOverlayAlreadyInitialized";
    case EVRInitError::VRInitError_Compositor_FailedToCreateMailbox:
        return "VRInitError_Compositor_FailedToCreateMailbox";
    case EVRInitError::VRInitError_Compositor_WindowInterfaceIsNull:
        return "VRInitError_Compositor_WindowInterfaceIsNull";
    case EVRInitError::VRInitError_Compositor_SystemLayerCreateInstance:
        return "VRInitError_Compositor_SystemLayerCreateInstance";
    case EVRInitError::VRInitError_Compositor_SystemLayerCreateSession:
        return "VRInitError_Compositor_SystemLayerCreateSession";
    case EVRInitError::VRInitError_Compositor_CreateInverseDistortUVs:
        return "VRInitError_Compositor_CreateInverseDistortUVs";
    case EVRInitError::VRInitError_Compositor_CreateBackbufferDepth:
        return "VRInitError_Compositor_CreateBackbufferDepth";
    case EVRInitError::VRInitError_Compositor_CannotDRMLeaseDisplay:
        return "VRInitError_Compositor_CannotDRMLeaseDisplay";
    case EVRInitError::VRInitError_Compositor_CannotConnectToDisplayServer:
        return "VRInitError_Compositor_CannotConnectToDisplayServer";
    case EVRInitError::VRInitError_Compositor_GnomeNoDRMLeasing:
        return "VRInitError_Compositor_GnomeNoDRMLeasing";
    case EVRInitError::VRInitError_Compositor_FailedToInitializeEncoder:
        return "VRInitError_Compositor_FailedToInitializeEncoder";
    case EVRInitError::VRInitError_Compositor_CreateBlurTexture:
        return "VRInitError_Compositor_CreateBlurTexture";
    case EVRInitError::VRInitError_VendorSpecific_UnableToConnectToOculusRuntime:
        return "VRInitError_VendorSpecific_UnableToConnectToOculusRuntime";
    case EVRInitError::VRInitError_VendorSpecific_WindowsNotInDevMode:
        return "VRInitError_VendorSpecific_WindowsNotInDevMode";
    case EVRInitError::VRInitError_VendorSpecific_OculusLinkNotEnabled:
        return "VRInitError_VendorSpecific_OculusLinkNotEnabled";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_CantOpenDevice:
        return "VRInitError_VendorSpecific_HmdFound_CantOpenDevice";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_UnableToRequestConfigStart:
        return "VRInitError_VendorSpecific_HmdFound_UnableToRequestConfigStart";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_NoStoredConfig:
        return "VRInitError_VendorSpecific_HmdFound_NoStoredConfig";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_ConfigTooBig:
        return "VRInitError_VendorSpecific_HmdFound_ConfigTooBig";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_ConfigTooSmall:
        return "VRInitError_VendorSpecific_HmdFound_ConfigTooSmall";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_UnableToInitZLib:
        return "VRInitError_VendorSpecific_HmdFound_UnableToInitZLib";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_CantReadFirmwareVersion:
        return "VRInitError_VendorSpecific_HmdFound_CantReadFirmwareVersion";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_UnableToSendUserDataStart:
        return "VRInitError_VendorSpecific_HmdFound_UnableToSendUserDataStart";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_UnableToGetUserDataStart:
        return "VRInitError_VendorSpecific_HmdFound_UnableToGetUserDataStart";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_UnableToGetUserDataNext:
        return "VRInitError_VendorSpecific_HmdFound_UnableToGetUserDataNext";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_UserDataAddressRange:
        return "VRInitError_VendorSpecific_HmdFound_UserDataAddressRange";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_UserDataError:
        return "VRInitError_VendorSpecific_HmdFound_UserDataError";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_ConfigFailedSanityCheck:
        return "VRInitError_VendorSpecific_HmdFound_ConfigFailedSanityCheck";
    case EVRInitError::VRInitError_VendorSpecific_OculusRuntimeBadInstall:
        return "VRInitError_VendorSpecific_OculusRuntimeBadInstall";
    case EVRInitError::VRInitError_VendorSpecific_HmdFound_UnexpectedConfiguration_1:
        return "VRInitError_VendorSpecific_HmdFound_UnexpectedConfiguration_1";
    case EVRInitError::VRInitError_Steam_SteamInstallationNotFound:
        return "VRInitError_Steam_SteamInstallationNotFound";
    case EVRInitError::VRInitError_LastError:
        return "VRInitError_LastError";
    default:
        return fmt::format("VRInitError_{}", (uint32_t)initErr);
    }
}

std::string format_as(ETrackedPropertyError trackedPropertyErr)
{
    switch (trackedPropertyErr) {
    case ETrackedPropertyError::TrackedProp_Success:
        return "TrackedProp_Success";
    case ETrackedPropertyError::TrackedProp_WrongDataType:
        return "TrackedProp_WrongDataType";
    case ETrackedPropertyError::TrackedProp_WrongDeviceClass:
        return "TrackedProp_WrongDeviceClass";
    case ETrackedPropertyError::TrackedProp_BufferTooSmall:
        return "TrackedProp_BufferTooSmall";
    case ETrackedPropertyError::TrackedProp_UnknownProperty:
        return "TrackedProp_UnknownProperty";
    case ETrackedPropertyError::TrackedProp_InvalidDevice:
        return "TrackedProp_InvalidDevice";
    case ETrackedPropertyError::TrackedProp_CouldNotContactServer:
        return "TrackedProp_CouldNotContactServer";
    case ETrackedPropertyError::TrackedProp_ValueNotProvidedByDevice:
        return "TrackedProp_ValueNotProvidedByDevice";
    case ETrackedPropertyError::TrackedProp_StringExceedsMaximumLength:
        return "TrackedProp_StringExceedsMaximumLength";
    case ETrackedPropertyError::TrackedProp_NotYetAvailable:
        return "TrackedProp_NotYetAvailable";
    case ETrackedPropertyError::TrackedProp_PermissionDenied:
        return "TrackedProp_PermissionDenied";
    case ETrackedPropertyError::TrackedProp_InvalidOperation:
        return "TrackedProp_InvalidOperation";
    case ETrackedPropertyError::TrackedProp_CannotWriteToWildcards:
        return "TrackedProp_CannotWriteToWildcards";
    case ETrackedPropertyError::TrackedProp_IPCReadFailure:
        return "TrackedProp_IPCReadFailure";
    case ETrackedPropertyError::TrackedProp_OutOfMemory:
        return "TrackedProp_OutOfMemory";
    case ETrackedPropertyError::TrackedProp_InvalidContainer:
        return "TrackedProp_InvalidContainer";
    default:
        return fmt::format("TrackedProp_{}", (uint32_t)trackedPropertyErr);
    }
}

std::string format_as(EVRInputError inputErr)
{
    switch (inputErr) {
    case EVRInputError::VRInputError_None:
        return "VRInputError_None";
    case EVRInputError::VRInputError_NameNotFound:
        return "VRInputError_NameNotFound";
    case EVRInputError::VRInputError_WrongType:
        return "VRInputError_WrongType";
    case EVRInputError::VRInputError_InvalidHandle:
        return "VRInputError_InvalidHandle";
    case EVRInputError::VRInputError_InvalidParam:
        return "VRInputError_InvalidParam";
    case EVRInputError::VRInputError_NoSteam:
        return "VRInputError_NoSteam";
    case EVRInputError::VRInputError_MaxCapacityReached:
        return "VRInputError_MaxCapacityReached";
    case EVRInputError::VRInputError_IPCError:
        return "VRInputError_IPCError";
    case EVRInputError::VRInputError_NoActiveActionSet:
        return "VRInputError_NoActiveActionSet";
    case EVRInputError::VRInputError_InvalidDevice:
        return "VRInputError_InvalidDevice";
    case EVRInputError::VRInputError_InvalidSkeleton:
        return "VRInputError_InvalidSkeleton";
    case EVRInputError::VRInputError_InvalidBoneCount:
        return "VRInputError_InvalidBoneCount";
    case EVRInputError::VRInputError_InvalidCompressedData:
        return "VRInputError_InvalidCompressedData";
    case EVRInputError::VRInputError_NoData:
        return "VRInputError_NoData";
    case EVRInputError::VRInputError_BufferTooSmall:
        return "VRInputError_BufferTooSmall";
    case EVRInputError::VRInputError_MismatchedActionManifest:
        return "VRInputError_MismatchedActionManifest";
    case EVRInputError::VRInputError_MissingSkeletonData:
        return "VRInputError_MissingSkeletonData";
    case EVRInputError::VRInputError_InvalidBoneIndex:
        return "VRInputError_InvalidBoneIndex";
    case EVRInputError::VRInputError_InvalidPriority:
        return "VRInputError_InvalidPriority";
    case EVRInputError::VRInputError_PermissionDenied:
        return "VRInputError_PermissionDenied";
    case EVRInputError::VRInputError_InvalidRenderModel:
        return "VRInputError_InvalidRenderModel";
    default:
        return fmt::format("VRInputError_{}", (uint32_t)inputErr);
    }
}

std::string format_as(EVRSpatialAnchorError spatialAnchorErr)
{
    switch (spatialAnchorErr) {
    case EVRSpatialAnchorError::VRSpatialAnchorError_Success:
        return "VRSpatialAnchorError_Success";
    case EVRSpatialAnchorError::VRSpatialAnchorError_Internal:
        return "VRSpatialAnchorError_Internal";
    case EVRSpatialAnchorError::VRSpatialAnchorError_UnknownHandle:
        return "VRSpatialAnchorError_UnknownHandle";
    case EVRSpatialAnchorError::VRSpatialAnchorError_ArrayTooSmall:
        return "VRSpatialAnchorError_ArrayTooSmall";
    case EVRSpatialAnchorError::VRSpatialAnchorError_InvalidDescriptorChar:
        return "VRSpatialAnchorError_InvalidDescriptorChar";
    case EVRSpatialAnchorError::VRSpatialAnchorError_NotYetAvailable:
        return "VRSpatialAnchorError_NotYetAvailable";
    case EVRSpatialAnchorError::VRSpatialAnchorError_NotAvailableInThisUniverse:
        return "VRSpatialAnchorError_NotAvailableInThisUniverse";
    case EVRSpatialAnchorError::VRSpatialAnchorError_PermanentlyUnavailable:
        return "VRSpatialAnchorError_PermanentlyUnavailable";
    case EVRSpatialAnchorError::VRSpatialAnchorError_WrongDriver:
        return "VRSpatialAnchorError_WrongDriver";
    case EVRSpatialAnchorError::VRSpatialAnchorError_DescriptorTooLong:
        return "VRSpatialAnchorError_DescriptorTooLong";
    case EVRSpatialAnchorError::VRSpatialAnchorError_Unknown:
        return "VRSpatialAnchorError_Unknown";
    case EVRSpatialAnchorError::VRSpatialAnchorError_NoRoomCalibration:
        return "VRSpatialAnchorError_NoRoomCalibration";
    case EVRSpatialAnchorError::VRSpatialAnchorError_InvalidArgument:
        return "VRSpatialAnchorError_InvalidArgument";
    case EVRSpatialAnchorError::VRSpatialAnchorError_UnknownDriver:
        return "VRSpatialAnchorError_UnknownDriver";
    default:
        return fmt::format("VRSpatialAnchorError_{}", (uint32_t)spatialAnchorErr);
    }
}

std::string format_as(EVRNotificationError notificationErr)
{
    switch (notificationErr) {
    case EVRNotificationError::VRNotificationError_OK:
        return "VRNotificationError_OK";
    case EVRNotificationError::VRNotificationError_InvalidNotificationId:
        return "VRNotificationError_InvalidNotificationId";
    case EVRNotificationError::VRNotificationError_NotificationQueueFull:
        return "VRNotificationError_NotificationQueueFull";
    case EVRNotificationError::VRNotificationError_InvalidOverlayHandle:
        return "VRNotificationError_InvalidOverlayHandle";
    case EVRNotificationError::VRNotificationError_SystemWithUserValueAlreadyExists:
        return "VRNotificationError_SystemWithUserValueAlreadyExists";
    case EVRNotificationError::VRNotificationError_ServiceUnavailable:
        return "VRNotificationError_ServiceUnavailable";
    default:
        return fmt::format("VRNotificationError_{}", (uint32_t)notificationErr);
    }
}

std::string format_as(ETrackedDeviceClass trackedDeviceClass)
{
    switch (trackedDeviceClass) {
    case ETrackedDeviceClass::TrackedDeviceClass_Invalid:
        return "TrackedDeviceClass_Invalid";
    case ETrackedDeviceClass::TrackedDeviceClass_HMD:
        return "TrackedDeviceClass_HMD";
    case ETrackedDeviceClass::TrackedDeviceClass_Controller:
        return "TrackedDeviceClass_Controller";
    case ETrackedDeviceClass::TrackedDeviceClass_GenericTracker:
        return "TrackedDeviceClass_GenericTracker";
    case ETrackedDeviceClass::TrackedDeviceClass_TrackingReference:
        return "TrackedDeviceClass_TrackingReference";
    case ETrackedDeviceClass::TrackedDeviceClass_DisplayRedirect:
        return "TrackedDeviceClass_DisplayRedirect";
    case ETrackedDeviceClass::TrackedDeviceClass_Max:
    default:
        return fmt::format("TrackedDeviceClass_{}", (uint32_t)trackedDeviceClass);
    }
}
std::string format_as(ETrackedDeviceProperty trackedDeviceProperty)
{
    switch (trackedDeviceProperty) {
    case ETrackedDeviceProperty::Prop_Invalid:
        return "Prop_Invalid";
    case ETrackedDeviceProperty::Prop_TrackingSystemName_String:
        return "Prop_TrackingSystemName_String";
    case ETrackedDeviceProperty::Prop_ModelNumber_String:
        return "Prop_ModelNumber_String";
    case ETrackedDeviceProperty::Prop_SerialNumber_String:
        return "Prop_SerialNumber_String";
    case ETrackedDeviceProperty::Prop_RenderModelName_String:
        return "Prop_RenderModelName_String";
    case ETrackedDeviceProperty::Prop_WillDriftInYaw_Bool:
        return "Prop_WillDriftInYaw_Bool";
    case ETrackedDeviceProperty::Prop_ManufacturerName_String:
        return "Prop_ManufacturerName_String";
    case ETrackedDeviceProperty::Prop_TrackingFirmwareVersion_String:
        return "Prop_TrackingFirmwareVersion_String";
    case ETrackedDeviceProperty::Prop_HardwareRevision_String:
        return "Prop_HardwareRevision_String";
    case ETrackedDeviceProperty::Prop_AllWirelessDongleDescriptions_String:
        return "Prop_AllWirelessDongleDescriptions_String";
    case ETrackedDeviceProperty::Prop_ConnectedWirelessDongle_String:
        return "Prop_ConnectedWirelessDongle_String";
    case ETrackedDeviceProperty::Prop_DeviceIsWireless_Bool:
        return "Prop_DeviceIsWireless_Bool";
    case ETrackedDeviceProperty::Prop_DeviceIsCharging_Bool:
        return "Prop_DeviceIsCharging_Bool";
    case ETrackedDeviceProperty::Prop_DeviceBatteryPercentage_Float:
        return "Prop_DeviceBatteryPercentage_Float";
    case ETrackedDeviceProperty::Prop_StatusDisplayTransform_Matrix34:
        return "Prop_StatusDisplayTransform_Matrix34";
    case ETrackedDeviceProperty::Prop_Firmware_UpdateAvailable_Bool:
        return "Prop_Firmware_UpdateAvailable_Bool";
    case ETrackedDeviceProperty::Prop_Firmware_ManualUpdate_Bool:
        return "Prop_Firmware_ManualUpdate_Bool";
    case ETrackedDeviceProperty::Prop_Firmware_ManualUpdateURL_String:
        return "Prop_Firmware_ManualUpdateURL_String";
    case ETrackedDeviceProperty::Prop_HardwareRevision_Uint64:
        return "Prop_HardwareRevision_Uint64";
    case ETrackedDeviceProperty::Prop_FirmwareVersion_Uint64:
        return "Prop_FirmwareVersion_Uint64";
    case ETrackedDeviceProperty::Prop_FPGAVersion_Uint64:
        return "Prop_FPGAVersion_Uint64";
    case ETrackedDeviceProperty::Prop_VRCVersion_Uint64:
        return "Prop_VRCVersion_Uint64";
    case ETrackedDeviceProperty::Prop_RadioVersion_Uint64:
        return "Prop_RadioVersion_Uint64";
    case ETrackedDeviceProperty::Prop_DongleVersion_Uint64:
        return "Prop_DongleVersion_Uint64";
    case ETrackedDeviceProperty::Prop_BlockServerShutdown_Bool:
        return "Prop_BlockServerShutdown_Bool";
    case ETrackedDeviceProperty::Prop_CanUnifyCoordinateSystemWithHmd_Bool:
        return "Prop_CanUnifyCoordinateSystemWithHmd_Bool";
    case ETrackedDeviceProperty::Prop_ContainsProximitySensor_Bool:
        return "Prop_ContainsProximitySensor_Bool";
    case ETrackedDeviceProperty::Prop_DeviceProvidesBatteryStatus_Bool:
        return "Prop_DeviceProvidesBatteryStatus_Bool";
    case ETrackedDeviceProperty::Prop_DeviceCanPowerOff_Bool:
        return "Prop_DeviceCanPowerOff_Bool";
    case ETrackedDeviceProperty::Prop_Firmware_ProgrammingTarget_String:
        return "Prop_Firmware_ProgrammingTarget_String";
    case ETrackedDeviceProperty::Prop_DeviceClass_Int32:
        return "Prop_DeviceClass_Int32";
    case ETrackedDeviceProperty::Prop_HasCamera_Bool:
        return "Prop_HasCamera_Bool";
    case ETrackedDeviceProperty::Prop_DriverVersion_String:
        return "Prop_DriverVersion_String";
    case ETrackedDeviceProperty::Prop_Firmware_ForceUpdateRequired_Bool:
        return "Prop_Firmware_ForceUpdateRequired_Bool";
    case ETrackedDeviceProperty::Prop_ViveSystemButtonFixRequired_Bool:
        return "Prop_ViveSystemButtonFixRequired_Bool";
    case ETrackedDeviceProperty::Prop_ParentDriver_Uint64:
        return "Prop_ParentDriver_Uint64";
    case ETrackedDeviceProperty::Prop_ResourceRoot_String:
        return "Prop_ResourceRoot_String";
    case ETrackedDeviceProperty::Prop_RegisteredDeviceType_String:
        return "Prop_RegisteredDeviceType_String";
    case ETrackedDeviceProperty::Prop_InputProfilePath_String:
        return "Prop_InputProfilePath_String";
    case ETrackedDeviceProperty::Prop_NeverTracked_Bool:
        return "Prop_NeverTracked_Bool";
    case ETrackedDeviceProperty::Prop_NumCameras_Int32:
        return "Prop_NumCameras_Int32";
    case ETrackedDeviceProperty::Prop_CameraFrameLayout_Int32:
        return "Prop_CameraFrameLayout_Int32";
    case ETrackedDeviceProperty::Prop_CameraStreamFormat_Int32:
        return "Prop_CameraStreamFormat_Int32";
    case ETrackedDeviceProperty::Prop_AdditionalDeviceSettingsPath_String:
        return "Prop_AdditionalDeviceSettingsPath_String";
    case ETrackedDeviceProperty::Prop_Identifiable_Bool:
        return "Prop_Identifiable_Bool";
    case ETrackedDeviceProperty::Prop_BootloaderVersion_Uint64:
        return "Prop_BootloaderVersion_Uint64";
    case ETrackedDeviceProperty::Prop_AdditionalSystemReportData_String:
        return "Prop_AdditionalSystemReportData_String";
    case ETrackedDeviceProperty::Prop_CompositeFirmwareVersion_String:
        return "Prop_CompositeFirmwareVersion_String";
    case ETrackedDeviceProperty::Prop_Firmware_RemindUpdate_Bool:
        return "Prop_Firmware_RemindUpdate_Bool";
    case ETrackedDeviceProperty::Prop_PeripheralApplicationVersion_Uint64:
        return "Prop_PeripheralApplicationVersion_Uint64";
    case ETrackedDeviceProperty::Prop_ManufacturerSerialNumber_String:
        return "Prop_ManufacturerSerialNumber_String";
    case ETrackedDeviceProperty::Prop_ComputedSerialNumber_String:
        return "Prop_ComputedSerialNumber_String";
    case ETrackedDeviceProperty::Prop_EstimatedDeviceFirstUseTime_Int32:
        return "Prop_EstimatedDeviceFirstUseTime_Int32";
    case ETrackedDeviceProperty::Prop_DevicePowerUsage_Float:
        return "Prop_DevicePowerUsage_Float";
    case ETrackedDeviceProperty::Prop_IgnoreMotionForStandby_Bool:
        return "Prop_IgnoreMotionForStandby_Bool";
    case ETrackedDeviceProperty::Prop_ActualTrackingSystemName_String:
        return "Prop_ActualTrackingSystemName_String";
    case ETrackedDeviceProperty::Prop_ReportsTimeSinceVSync_Bool:
        return "Prop_ReportsTimeSinceVSync_Bool";
    case ETrackedDeviceProperty::Prop_SecondsFromVsyncToPhotons_Float:
        return "Prop_SecondsFromVsyncToPhotons_Float";
    case ETrackedDeviceProperty::Prop_DisplayFrequency_Float:
        return "Prop_DisplayFrequency_Float";
    case ETrackedDeviceProperty::Prop_UserIpdMeters_Float:
        return "Prop_UserIpdMeters_Float";
    case ETrackedDeviceProperty::Prop_CurrentUniverseId_Uint64:
        return "Prop_CurrentUniverseId_Uint64";
    case ETrackedDeviceProperty::Prop_PreviousUniverseId_Uint64:
        return "Prop_PreviousUniverseId_Uint64";
    case ETrackedDeviceProperty::Prop_DisplayFirmwareVersion_Uint64:
        return "Prop_DisplayFirmwareVersion_Uint64";
    case ETrackedDeviceProperty::Prop_IsOnDesktop_Bool:
        return "Prop_IsOnDesktop_Bool";
    case ETrackedDeviceProperty::Prop_DisplayMCType_Int32:
        return "Prop_DisplayMCType_Int32";
    case ETrackedDeviceProperty::Prop_DisplayMCOffset_Float:
        return "Prop_DisplayMCOffset_Float";
    case ETrackedDeviceProperty::Prop_DisplayMCScale_Float:
        return "Prop_DisplayMCScale_Float";
    case ETrackedDeviceProperty::Prop_EdidVendorID_Int32:
        return "Prop_EdidVendorID_Int32";
    case ETrackedDeviceProperty::Prop_DisplayMCImageLeft_String:
        return "Prop_DisplayMCImageLeft_String";
    case ETrackedDeviceProperty::Prop_DisplayMCImageRight_String:
        return "Prop_DisplayMCImageRight_String";
    case ETrackedDeviceProperty::Prop_DisplayGCBlackClamp_Float:
        return "Prop_DisplayGCBlackClamp_Float";
    case ETrackedDeviceProperty::Prop_EdidProductID_Int32:
        return "Prop_EdidProductID_Int32";
    case ETrackedDeviceProperty::Prop_CameraToHeadTransform_Matrix34:
        return "Prop_CameraToHeadTransform_Matrix34";
    case ETrackedDeviceProperty::Prop_DisplayGCType_Int32:
        return "Prop_DisplayGCType_Int32";
    case ETrackedDeviceProperty::Prop_DisplayGCOffset_Float:
        return "Prop_DisplayGCOffset_Float";
    case ETrackedDeviceProperty::Prop_DisplayGCScale_Float:
        return "Prop_DisplayGCScale_Float";
    case ETrackedDeviceProperty::Prop_DisplayGCPrescale_Float:
        return "Prop_DisplayGCPrescale_Float";
    case ETrackedDeviceProperty::Prop_DisplayGCImage_String:
        return "Prop_DisplayGCImage_String";
    case ETrackedDeviceProperty::Prop_LensCenterLeftU_Float:
        return "Prop_LensCenterLeftU_Float";
    case ETrackedDeviceProperty::Prop_LensCenterLeftV_Float:
        return "Prop_LensCenterLeftV_Float";
    case ETrackedDeviceProperty::Prop_LensCenterRightU_Float:
        return "Prop_LensCenterRightU_Float";
    case ETrackedDeviceProperty::Prop_LensCenterRightV_Float:
        return "Prop_LensCenterRightV_Float";
    case ETrackedDeviceProperty::Prop_UserHeadToEyeDepthMeters_Float:
        return "Prop_UserHeadToEyeDepthMeters_Float";
    case ETrackedDeviceProperty::Prop_CameraFirmwareVersion_Uint64:
        return "Prop_CameraFirmwareVersion_Uint64";
    case ETrackedDeviceProperty::Prop_CameraFirmwareDescription_String:
        return "Prop_CameraFirmwareDescription_String";
    case ETrackedDeviceProperty::Prop_DisplayFPGAVersion_Uint64:
        return "Prop_DisplayFPGAVersion_Uint64";
    case ETrackedDeviceProperty::Prop_DisplayBootloaderVersion_Uint64:
        return "Prop_DisplayBootloaderVersion_Uint64";
    case ETrackedDeviceProperty::Prop_DisplayHardwareVersion_Uint64:
        return "Prop_DisplayHardwareVersion_Uint64";
    case ETrackedDeviceProperty::Prop_AudioFirmwareVersion_Uint64:
        return "Prop_AudioFirmwareVersion_Uint64";
    case ETrackedDeviceProperty::Prop_CameraCompatibilityMode_Int32:
        return "Prop_CameraCompatibilityMode_Int32";
    case ETrackedDeviceProperty::Prop_ScreenshotHorizontalFieldOfViewDegrees_Float:
        return "Prop_ScreenshotHorizontalFieldOfViewDegrees_Float";
    case ETrackedDeviceProperty::Prop_ScreenshotVerticalFieldOfViewDegrees_Float:
        return "Prop_ScreenshotVerticalFieldOfViewDegrees_Float";
    case ETrackedDeviceProperty::Prop_DisplaySuppressed_Bool:
        return "Prop_DisplaySuppressed_Bool";
    case ETrackedDeviceProperty::Prop_DisplayAllowNightMode_Bool:
        return "Prop_DisplayAllowNightMode_Bool";
    case ETrackedDeviceProperty::Prop_DisplayMCImageWidth_Int32:
        return "Prop_DisplayMCImageWidth_Int32";
    case ETrackedDeviceProperty::Prop_DisplayMCImageHeight_Int32:
        return "Prop_DisplayMCImageHeight_Int32";
    case ETrackedDeviceProperty::Prop_DisplayMCImageNumChannels_Int32:
        return "Prop_DisplayMCImageNumChannels_Int32";
    case ETrackedDeviceProperty::Prop_DisplayMCImageData_Binary:
        return "Prop_DisplayMCImageData_Binary";
    case ETrackedDeviceProperty::Prop_SecondsFromPhotonsToVblank_Float:
        return "Prop_SecondsFromPhotonsToVblank_Float";
    case ETrackedDeviceProperty::Prop_DriverDirectModeSendsVsyncEvents_Bool:
        return "Prop_DriverDirectModeSendsVsyncEvents_Bool";
    case ETrackedDeviceProperty::Prop_DisplayDebugMode_Bool:
        return "Prop_DisplayDebugMode_Bool";
    case ETrackedDeviceProperty::Prop_GraphicsAdapterLuid_Uint64:
        return "Prop_GraphicsAdapterLuid_Uint64";
    case ETrackedDeviceProperty::Prop_DriverProvidedChaperonePath_String:
        return "Prop_DriverProvidedChaperonePath_String";
    case ETrackedDeviceProperty::Prop_ExpectedTrackingReferenceCount_Int32:
        return "Prop_ExpectedTrackingReferenceCount_Int32";
    case ETrackedDeviceProperty::Prop_ExpectedControllerCount_Int32:
        return "Prop_ExpectedControllerCount_Int32";
    case ETrackedDeviceProperty::Prop_NamedIconPathControllerLeftDeviceOff_String:
        return "Prop_NamedIconPathControllerLeftDeviceOff_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathControllerRightDeviceOff_String:
        return "Prop_NamedIconPathControllerRightDeviceOff_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathTrackingReferenceDeviceOff_String:
        return "Prop_NamedIconPathTrackingReferenceDeviceOff_String";
    case ETrackedDeviceProperty::Prop_DoNotApplyPrediction_Bool:
        return "Prop_DoNotApplyPrediction_Bool";
    case ETrackedDeviceProperty::Prop_CameraToHeadTransforms_Matrix34_Array:
        return "Prop_CameraToHeadTransforms_Matrix34_Array";
    case ETrackedDeviceProperty::Prop_DistortionMeshResolution_Int32:
        return "Prop_DistortionMeshResolution_Int32";
    case ETrackedDeviceProperty::Prop_DriverIsDrawingControllers_Bool:
        return "Prop_DriverIsDrawingControllers_Bool";
    case ETrackedDeviceProperty::Prop_DriverRequestsApplicationPause_Bool:
        return "Prop_DriverRequestsApplicationPause_Bool";
    case ETrackedDeviceProperty::Prop_DriverRequestsReducedRendering_Bool:
        return "Prop_DriverRequestsReducedRendering_Bool";
    case ETrackedDeviceProperty::Prop_MinimumIpdStepMeters_Float:
        return "Prop_MinimumIpdStepMeters_Float";
    case ETrackedDeviceProperty::Prop_AudioBridgeFirmwareVersion_Uint64:
        return "Prop_AudioBridgeFirmwareVersion_Uint64";
    case ETrackedDeviceProperty::Prop_ImageBridgeFirmwareVersion_Uint64:
        return "Prop_ImageBridgeFirmwareVersion_Uint64";
    case ETrackedDeviceProperty::Prop_ImuToHeadTransform_Matrix34:
        return "Prop_ImuToHeadTransform_Matrix34";
    case ETrackedDeviceProperty::Prop_ImuFactoryGyroBias_Vector3:
        return "Prop_ImuFactoryGyroBias_Vector3";
    case ETrackedDeviceProperty::Prop_ImuFactoryGyroScale_Vector3:
        return "Prop_ImuFactoryGyroScale_Vector3";
    case ETrackedDeviceProperty::Prop_ImuFactoryAccelerometerBias_Vector3:
        return "Prop_ImuFactoryAccelerometerBias_Vector3";
    case ETrackedDeviceProperty::Prop_ImuFactoryAccelerometerScale_Vector3:
        return "Prop_ImuFactoryAccelerometerScale_Vector3";
    case ETrackedDeviceProperty::Prop_ConfigurationIncludesLighthouse20Features_Bool:
        return "Prop_ConfigurationIncludesLighthouse20Features_Bool";
    case ETrackedDeviceProperty::Prop_AdditionalRadioFeatures_Uint64:
        return "Prop_AdditionalRadioFeatures_Uint64";
    case ETrackedDeviceProperty::Prop_CameraWhiteBalance_Vector4_Array:
        return "Prop_CameraWhiteBalance_Vector4_Array";
    case ETrackedDeviceProperty::Prop_CameraDistortionFunction_Int32_Array:
        return "Prop_CameraDistortionFunction_Int32_Array";
    case ETrackedDeviceProperty::Prop_CameraDistortionCoefficients_Float_Array:
        return "Prop_CameraDistortionCoefficients_Float_Array";
    case ETrackedDeviceProperty::Prop_ExpectedControllerType_String:
        return "Prop_ExpectedControllerType_String";
    case ETrackedDeviceProperty::Prop_HmdTrackingStyle_Int32:
        return "Prop_HmdTrackingStyle_Int32";
    case ETrackedDeviceProperty::Prop_DriverProvidedChaperoneVisibility_Bool:
        return "Prop_DriverProvidedChaperoneVisibility_Bool";
    case ETrackedDeviceProperty::Prop_HmdColumnCorrectionSettingPrefix_String:
        return "Prop_HmdColumnCorrectionSettingPrefix_String";
    case ETrackedDeviceProperty::Prop_CameraSupportsCompatibilityModes_Bool:
        return "Prop_CameraSupportsCompatibilityModes_Bool";
    case ETrackedDeviceProperty::Prop_SupportsRoomViewDepthProjection_Bool:
        return "Prop_SupportsRoomViewDepthProjection_Bool";
    case ETrackedDeviceProperty::Prop_DisplayAvailableFrameRates_Float_Array:
        return "Prop_DisplayAvailableFrameRates_Float_Array";
    case ETrackedDeviceProperty::Prop_DisplaySupportsMultipleFramerates_Bool:
        return "Prop_DisplaySupportsMultipleFramerates_Bool";
    case ETrackedDeviceProperty::Prop_DisplayColorMultLeft_Vector3:
        return "Prop_DisplayColorMultLeft_Vector3";
    case ETrackedDeviceProperty::Prop_DisplayColorMultRight_Vector3:
        return "Prop_DisplayColorMultRight_Vector3";
    case ETrackedDeviceProperty::Prop_DisplaySupportsRuntimeFramerateChange_Bool:
        return "Prop_DisplaySupportsRuntimeFramerateChange_Bool";
    case ETrackedDeviceProperty::Prop_DisplaySupportsAnalogGain_Bool:
        return "Prop_DisplaySupportsAnalogGain_Bool";
    case ETrackedDeviceProperty::Prop_DisplayMinAnalogGain_Float:
        return "Prop_DisplayMinAnalogGain_Float";
    case ETrackedDeviceProperty::Prop_DisplayMaxAnalogGain_Float:
        return "Prop_DisplayMaxAnalogGain_Float";
    case ETrackedDeviceProperty::Prop_CameraExposureTime_Float:
        return "Prop_CameraExposureTime_Float";
    case ETrackedDeviceProperty::Prop_CameraGlobalGain_Float:
        return "Prop_CameraGlobalGain_Float";
    case ETrackedDeviceProperty::Prop_DashboardScale_Float:
        return "Prop_DashboardScale_Float";
    case ETrackedDeviceProperty::Prop_Hmd_SupportsHDR10_Bool:
        return "Prop_Hmd_SupportsHDR10_Bool";
    case ETrackedDeviceProperty::Prop_Hmd_EnableParallelRenderCameras_Bool:
        return "Prop_Hmd_EnableParallelRenderCameras_Bool";
    case ETrackedDeviceProperty::Prop_DriverProvidedChaperoneJson_String:
        return "Prop_DriverProvidedChaperoneJson_String";
    case ETrackedDeviceProperty::Prop_ForceSystemLayerUseAppPoses_Bool:
        return "Prop_ForceSystemLayerUseAppPoses_Bool";
    case ETrackedDeviceProperty::Prop_IpdUIRangeMinMeters_Float:
        return "Prop_IpdUIRangeMinMeters_Float";
    case ETrackedDeviceProperty::Prop_IpdUIRangeMaxMeters_Float:
        return "Prop_IpdUIRangeMaxMeters_Float";
    case ETrackedDeviceProperty::Prop_Hmd_SupportsHDCP14LegacyCompat_Bool:
        return "Prop_Hmd_SupportsHDCP14LegacyCompat_Bool";
    case ETrackedDeviceProperty::Prop_Hmd_SupportsMicMonitoring_Bool:
        return "Prop_Hmd_SupportsMicMonitoring_Bool";
    case ETrackedDeviceProperty::Prop_Hmd_SupportsDisplayPortTrainingMode_Bool:
        return "Prop_Hmd_SupportsDisplayPortTrainingMode_Bool";
    case ETrackedDeviceProperty::Prop_Hmd_SupportsRoomViewDirect_Bool:
        return "Prop_Hmd_SupportsRoomViewDirect_Bool";
    case ETrackedDeviceProperty::Prop_Hmd_SupportsAppThrottling_Bool:
        return "Prop_Hmd_SupportsAppThrottling_Bool";
    case ETrackedDeviceProperty::Prop_Hmd_SupportsGpuBusMonitoring_Bool:
        return "Prop_Hmd_SupportsGpuBusMonitoring_Bool";
    case ETrackedDeviceProperty::Prop_DriverDisplaysIPDChanges_Bool:
        return "Prop_DriverDisplaysIPDChanges_Bool";
    case ETrackedDeviceProperty::Prop_Hmd_MaxDistortedTextureWidth_Int32:
        return "Prop_Hmd_MaxDistortedTextureWidth_Int32";
    case ETrackedDeviceProperty::Prop_Hmd_MaxDistortedTextureHeight_Int32:
        return "Prop_Hmd_MaxDistortedTextureHeight_Int32";
    case ETrackedDeviceProperty::Prop_Hmd_AllowSupersampleFiltering_Bool:
        return "Prop_Hmd_AllowSupersampleFiltering_Bool";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraCorrectionMode_Int32:
        return "Prop_DriverRequestedMuraCorrectionMode_Int32";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraFeather_InnerLeft_Int32:
        return "Prop_DriverRequestedMuraFeather_InnerLeft_Int32";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraFeather_InnerRight_Int32:
        return "Prop_DriverRequestedMuraFeather_InnerRight_Int32";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraFeather_InnerTop_Int32:
        return "Prop_DriverRequestedMuraFeather_InnerTop_Int32";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraFeather_InnerBottom_Int32:
        return "Prop_DriverRequestedMuraFeather_InnerBottom_Int32";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraFeather_OuterLeft_Int32:
        return "Prop_DriverRequestedMuraFeather_OuterLeft_Int32";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraFeather_OuterRight_Int32:
        return "Prop_DriverRequestedMuraFeather_OuterRight_Int32";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraFeather_OuterTop_Int32:
        return "Prop_DriverRequestedMuraFeather_OuterTop_Int32";
    case ETrackedDeviceProperty::Prop_DriverRequestedMuraFeather_OuterBottom_Int32:
        return "Prop_DriverRequestedMuraFeather_OuterBottom_Int32";
    case ETrackedDeviceProperty::Prop_Audio_DefaultPlaybackDeviceId_String:
        return "Prop_Audio_DefaultPlaybackDeviceId_String";
    case ETrackedDeviceProperty::Prop_Audio_DefaultRecordingDeviceId_String:
        return "Prop_Audio_DefaultRecordingDeviceId_String";
    case ETrackedDeviceProperty::Prop_Audio_DefaultPlaybackDeviceVolume_Float:
        return "Prop_Audio_DefaultPlaybackDeviceVolume_Float";
    case ETrackedDeviceProperty::Prop_Audio_SupportsDualSpeakerAndJackOutput_Bool:
        return "Prop_Audio_SupportsDualSpeakerAndJackOutput_Bool";
    case ETrackedDeviceProperty::Prop_Audio_DriverManagesPlaybackVolumeControl_Bool:
        return "Prop_Audio_DriverManagesPlaybackVolumeControl_Bool";
    case ETrackedDeviceProperty::Prop_Audio_DriverPlaybackVolume_Float:
        return "Prop_Audio_DriverPlaybackVolume_Float";
    case ETrackedDeviceProperty::Prop_Audio_DriverPlaybackMute_Bool:
        return "Prop_Audio_DriverPlaybackMute_Bool";
    case ETrackedDeviceProperty::Prop_Audio_DriverManagesRecordingVolumeControl_Bool:
        return "Prop_Audio_DriverManagesRecordingVolumeControl_Bool";
    case ETrackedDeviceProperty::Prop_Audio_DriverRecordingVolume_Float:
        return "Prop_Audio_DriverRecordingVolume_Float";
    case ETrackedDeviceProperty::Prop_Audio_DriverRecordingMute_Bool:
        return "Prop_Audio_DriverRecordingMute_Bool";
    case ETrackedDeviceProperty::Prop_AttachedDeviceId_String:
        return "Prop_AttachedDeviceId_String";
    case ETrackedDeviceProperty::Prop_SupportedButtons_Uint64:
        return "Prop_SupportedButtons_Uint64";
    case ETrackedDeviceProperty::Prop_Axis0Type_Int32:
        return "Prop_Axis0Type_Int32";
    case ETrackedDeviceProperty::Prop_Axis1Type_Int32:
        return "Prop_Axis1Type_Int32";
    case ETrackedDeviceProperty::Prop_Axis2Type_Int32:
        return "Prop_Axis2Type_Int32";
    case ETrackedDeviceProperty::Prop_Axis3Type_Int32:
        return "Prop_Axis3Type_Int32";
    case ETrackedDeviceProperty::Prop_Axis4Type_Int32:
        return "Prop_Axis4Type_Int32";
    case ETrackedDeviceProperty::Prop_ControllerRoleHint_Int32:
        return "Prop_ControllerRoleHint_Int32";
    case ETrackedDeviceProperty::Prop_FieldOfViewLeftDegrees_Float:
        return "Prop_FieldOfViewLeftDegrees_Float";
    case ETrackedDeviceProperty::Prop_FieldOfViewRightDegrees_Float:
        return "Prop_FieldOfViewRightDegrees_Float";
    case ETrackedDeviceProperty::Prop_FieldOfViewTopDegrees_Float:
        return "Prop_FieldOfViewTopDegrees_Float";
    case ETrackedDeviceProperty::Prop_FieldOfViewBottomDegrees_Float:
        return "Prop_FieldOfViewBottomDegrees_Float";
    case ETrackedDeviceProperty::Prop_TrackingRangeMinimumMeters_Float:
        return "Prop_TrackingRangeMinimumMeters_Float";
    case ETrackedDeviceProperty::Prop_TrackingRangeMaximumMeters_Float:
        return "Prop_TrackingRangeMaximumMeters_Float";
    case ETrackedDeviceProperty::Prop_ModeLabel_String:
        return "Prop_ModeLabel_String";
    case ETrackedDeviceProperty::Prop_CanWirelessIdentify_Bool:
        return "Prop_CanWirelessIdentify_Bool";
    case ETrackedDeviceProperty::Prop_Nonce_Int32:
        return "Prop_Nonce_Int32";
    case ETrackedDeviceProperty::Prop_IconPathName_String:
        return "Prop_IconPathName_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceOff_String:
        return "Prop_NamedIconPathDeviceOff_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceSearching_String:
        return "Prop_NamedIconPathDeviceSearching_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceSearchingAlert_String:
        return "Prop_NamedIconPathDeviceSearchingAlert_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceReady_String:
        return "Prop_NamedIconPathDeviceReady_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceReadyAlert_String:
        return "Prop_NamedIconPathDeviceReadyAlert_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceNotReady_String:
        return "Prop_NamedIconPathDeviceNotReady_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceStandby_String:
        return "Prop_NamedIconPathDeviceStandby_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceAlertLow_String:
        return "Prop_NamedIconPathDeviceAlertLow_String";
    case ETrackedDeviceProperty::Prop_NamedIconPathDeviceStandbyAlert_String:
        return "Prop_NamedIconPathDeviceStandbyAlert_String";
    case ETrackedDeviceProperty::Prop_DisplayHiddenArea_Binary_Start:
        return "Prop_DisplayHiddenArea_Binary_Start";
    case ETrackedDeviceProperty::Prop_DisplayHiddenArea_Binary_End:
        return "Prop_DisplayHiddenArea_Binary_End";
    case ETrackedDeviceProperty::Prop_ParentContainer:
        return "Prop_ParentContainer";
    case ETrackedDeviceProperty::Prop_OverrideContainer_Uint64:
        return "Prop_OverrideContainer_Uint64";
    case ETrackedDeviceProperty::Prop_UserConfigPath_String:
        return "Prop_UserConfigPath_String";
    case ETrackedDeviceProperty::Prop_InstallPath_String:
        return "Prop_InstallPath_String";
    case ETrackedDeviceProperty::Prop_HasDisplayComponent_Bool:
        return "Prop_HasDisplayComponent_Bool";
    case ETrackedDeviceProperty::Prop_HasControllerComponent_Bool:
        return "Prop_HasControllerComponent_Bool";
    case ETrackedDeviceProperty::Prop_HasCameraComponent_Bool:
        return "Prop_HasCameraComponent_Bool";
    case ETrackedDeviceProperty::Prop_HasDriverDirectModeComponent_Bool:
        return "Prop_HasDriverDirectModeComponent_Bool";
    case ETrackedDeviceProperty::Prop_HasVirtualDisplayComponent_Bool:
        return "Prop_HasVirtualDisplayComponent_Bool";
    case ETrackedDeviceProperty::Prop_HasSpatialAnchorsSupport_Bool:
        return "Prop_HasSpatialAnchorsSupport_Bool";
    case ETrackedDeviceProperty::Prop_SupportsXrTextureSets_Bool:
        return "Prop_SupportsXrTextureSets_Bool";
    case ETrackedDeviceProperty::Prop_ControllerType_String:
        return "Prop_ControllerType_String";
    case ETrackedDeviceProperty::Prop_ControllerHandSelectionPriority_Int32:
        return "Prop_ControllerHandSelectionPriority_Int32";
    case ETrackedDeviceProperty::Prop_VendorSpecific_Reserved_Start:
        return "Prop_VendorSpecific_Reserved_Start";
    case ETrackedDeviceProperty::Prop_VendorSpecific_Reserved_End:
        return "Prop_VendorSpecific_Reserved_End";
    case ETrackedDeviceProperty::Prop_TrackedDeviceProperty_Max:
        return "Prop_TrackedDeviceProperty_Max";
    default:
        return fmt::format("ETrackedDeviceProperty_{}", (uint32_t)trackedDeviceProperty);
    }
}
std::string format_as(EVRSettingsError settingsError)
{
    switch (settingsError) {
    case EVRSettingsError::VRSettingsError_None:
        return "VRSettingsError_None";
    case EVRSettingsError::VRSettingsError_IPCFailed:
        return "VRSettingsError_IPCFailed";
    case EVRSettingsError::VRSettingsError_WriteFailed:
        return "VRSettingsError_WriteFailed";
    case EVRSettingsError::VRSettingsError_ReadFailed:
        return "VRSettingsError_ReadFailed";
    case EVRSettingsError::VRSettingsError_JsonParseFailed:
        return "VRSettingsError_JsonParseFailed";
    case EVRSettingsError::VRSettingsError_UnsetSettingHasNoDefault:
        return "VRSettingsError_UnsetSettingHasNoDefault";
    case EVRSettingsError::VRSettingsError_AccessDenied:
        return "VRSettingsError_AccessDenied";
    default:
        return fmt::format("VRSettingsError_{}", (uint32_t)settingsError);
    }
}

std::string format_as(ETrackedControllerRole controllerRole)
{
    switch (controllerRole) {
    case ETrackedControllerRole::TrackedControllerRole_Invalid:
        return "TrackedControllerRole_Invalid";
    case ETrackedControllerRole::TrackedControllerRole_LeftHand:
        return "TrackedControllerRole_LeftHand";
    case ETrackedControllerRole::TrackedControllerRole_RightHand:
        return "TrackedControllerRole_RightHand";
    case ETrackedControllerRole::TrackedControllerRole_OptOut:
        return "TrackedControllerRole_OptOut";
    case ETrackedControllerRole::TrackedControllerRole_Treadmill:
        return "TrackedControllerRole_Treadmill";
    case ETrackedControllerRole::TrackedControllerRole_Stylus:
        return "TrackedControllerRole_Stylus";
    default:
        return fmt::format("TrackedControllerRole_{}", (uint32_t)controllerRole);
    }
}
std::string format_as(EVREventType eventType)
{
    switch (eventType) {
    case EVREventType::VREvent_None:
        return "VREvent_None";
    case EVREventType::VREvent_TrackedDeviceActivated:
        return "VREvent_TrackedDeviceActivated";
    case EVREventType::VREvent_TrackedDeviceDeactivated:
        return "VREvent_TrackedDeviceDeactivated";
    case EVREventType::VREvent_TrackedDeviceUpdated:
        return "VREvent_TrackedDeviceUpdated";
    case EVREventType::VREvent_TrackedDeviceUserInteractionStarted:
        return "VREvent_TrackedDeviceUserInteractionStarted";
    case EVREventType::VREvent_TrackedDeviceUserInteractionEnded:
        return "VREvent_TrackedDeviceUserInteractionEnded";
    case EVREventType::VREvent_IpdChanged:
        return "VREvent_IpdChanged";
    case EVREventType::VREvent_EnterStandbyMode:
        return "VREvent_EnterStandbyMode";
    case EVREventType::VREvent_LeaveStandbyMode:
        return "VREvent_LeaveStandbyMode";
    case EVREventType::VREvent_TrackedDeviceRoleChanged:
        return "VREvent_TrackedDeviceRoleChanged";
    case EVREventType::VREvent_WatchdogWakeUpRequested:
        return "VREvent_WatchdogWakeUpRequested";
    case EVREventType::VREvent_LensDistortionChanged:
        return "VREvent_LensDistortionChanged";
    case EVREventType::VREvent_PropertyChanged:
        return "VREvent_PropertyChanged";
    case EVREventType::VREvent_WirelessDisconnect:
        return "VREvent_WirelessDisconnect";
    case EVREventType::VREvent_WirelessReconnect:
        return "VREvent_WirelessReconnect";
    case EVREventType::VREvent_ButtonPress:
        return "VREvent_ButtonPress";
    case EVREventType::VREvent_ButtonUnpress:
        return "VREvent_ButtonUnpress";
    case EVREventType::VREvent_ButtonTouch:
        return "VREvent_ButtonTouch";
    case EVREventType::VREvent_ButtonUntouch:
        return "VREvent_ButtonUntouch";
    case EVREventType::VREvent_Modal_Cancel:
        return "VREvent_Modal_Cancel";
    case EVREventType::VREvent_MouseMove:
        return "VREvent_MouseMove";
    case EVREventType::VREvent_MouseButtonDown:
        return "VREvent_MouseButtonDown";
    case EVREventType::VREvent_MouseButtonUp:
        return "VREvent_MouseButtonUp";
    case EVREventType::VREvent_FocusEnter:
        return "VREvent_FocusEnter";
    case EVREventType::VREvent_FocusLeave:
        return "VREvent_FocusLeave";
    case EVREventType::VREvent_ScrollDiscrete:
        return "VREvent_ScrollDiscrete";
    case EVREventType::VREvent_TouchPadMove:
        return "VREvent_TouchPadMove";
    case EVREventType::VREvent_OverlayFocusChanged:
        return "VREvent_OverlayFocusChanged";
    case EVREventType::VREvent_ReloadOverlays:
        return "VREvent_ReloadOverlays";
    case EVREventType::VREvent_ScrollSmooth:
        return "VREvent_ScrollSmooth";
    case EVREventType::VREvent_LockMousePosition:
        return "VREvent_LockMousePosition";
    case EVREventType::VREvent_UnlockMousePosition:
        return "VREvent_UnlockMousePosition";
    case EVREventType::VREvent_InputFocusCaptured:
        return "VREvent_InputFocusCaptured";
    case EVREventType::VREvent_InputFocusReleased:
        return "VREvent_InputFocusReleased";
    case EVREventType::VREvent_SceneApplicationChanged:
        return "VREvent_SceneApplicationChanged";
    case EVREventType::VREvent_InputFocusChanged:
        return "VREvent_InputFocusChanged";
    case EVREventType::VREvent_SceneApplicationUsingWrongGraphicsAdapter:
        return "VREvent_SceneApplicationUsingWrongGraphicsAdapter";
    case EVREventType::VREvent_ActionBindingReloaded:
        return "VREvent_ActionBindingReloaded";
    case EVREventType::VREvent_HideRenderModels:
        return "VREvent_HideRenderModels";
    case EVREventType::VREvent_ShowRenderModels:
        return "VREvent_ShowRenderModels";
    case EVREventType::VREvent_SceneApplicationStateChanged:
        return "VREvent_SceneApplicationStateChanged";
    case EVREventType::VREvent_SceneAppPipeDisconnected:
        return "VREvent_SceneAppPipeDisconnected";
    case EVREventType::VREvent_ConsoleOpened:
        return "VREvent_ConsoleOpened";
    case EVREventType::VREvent_ConsoleClosed:
        return "VREvent_ConsoleClosed";
    case EVREventType::VREvent_OverlayShown:
        return "VREvent_OverlayShown";
    case EVREventType::VREvent_OverlayHidden:
        return "VREvent_OverlayHidden";
    case EVREventType::VREvent_DashboardActivated:
        return "VREvent_DashboardActivated";
    case EVREventType::VREvent_DashboardDeactivated:
        return "VREvent_DashboardDeactivated";
    case EVREventType::VREvent_ResetDashboard:
        return "VREvent_ResetDashboard";
    case EVREventType::VREvent_ImageLoaded:
        return "VREvent_ImageLoaded";
    case EVREventType::VREvent_ShowKeyboard:
        return "VREvent_ShowKeyboard";
    case EVREventType::VREvent_HideKeyboard:
        return "VREvent_HideKeyboard";
    case EVREventType::VREvent_OverlayGamepadFocusGained:
        return "VREvent_OverlayGamepadFocusGained";
    case EVREventType::VREvent_OverlayGamepadFocusLost:
        return "VREvent_OverlayGamepadFocusLost";
    case EVREventType::VREvent_OverlaySharedTextureChanged:
        return "VREvent_OverlaySharedTextureChanged";
    case EVREventType::VREvent_ScreenshotTriggered:
        return "VREvent_ScreenshotTriggered";
    case EVREventType::VREvent_ImageFailed:
        return "VREvent_ImageFailed";
    case EVREventType::VREvent_DashboardOverlayCreated:
        return "VREvent_DashboardOverlayCreated";
    case EVREventType::VREvent_SwitchGamepadFocus:
        return "VREvent_SwitchGamepadFocus";
    case EVREventType::VREvent_RequestScreenshot:
        return "VREvent_RequestScreenshot";
    case EVREventType::VREvent_ScreenshotTaken:
        return "VREvent_ScreenshotTaken";
    case EVREventType::VREvent_ScreenshotFailed:
        return "VREvent_ScreenshotFailed";
    case EVREventType::VREvent_SubmitScreenshotToDashboard:
        return "VREvent_SubmitScreenshotToDashboard";
    case EVREventType::VREvent_ScreenshotProgressToDashboard:
        return "VREvent_ScreenshotProgressToDashboard";
    case EVREventType::VREvent_PrimaryDashboardDeviceChanged:
        return "VREvent_PrimaryDashboardDeviceChanged";
    case EVREventType::VREvent_RoomViewShown:
        return "VREvent_RoomViewShown";
    case EVREventType::VREvent_RoomViewHidden:
        return "VREvent_RoomViewHidden";
    case EVREventType::VREvent_ShowUI:
        return "VREvent_ShowUI";
    case EVREventType::VREvent_ShowDevTools:
        return "VREvent_ShowDevTools";
    case EVREventType::VREvent_DesktopViewUpdating:
        return "VREvent_DesktopViewUpdating";
    case EVREventType::VREvent_DesktopViewReady:
        return "VREvent_DesktopViewReady";
    case EVREventType::VREvent_StartDashboard:
        return "VREvent_StartDashboard";
    case EVREventType::VREvent_ElevatePrism:
        return "VREvent_ElevatePrism";
    case EVREventType::VREvent_OverlayClosed:
        return "VREvent_OverlayClosed";
    case EVREventType::VREvent_DashboardThumbChanged:
        return "VREvent_DashboardThumbChanged";
    case EVREventType::VREvent_DesktopMightBeVisible:
        return "VREvent_DesktopMightBeVisible";
    case EVREventType::VREvent_DesktopMightBeHidden:
        return "VREvent_DesktopMightBeHidden";
    case EVREventType::VREvent_MutualSteamCapabilitiesChanged:
        return "VREvent_MutualSteamCapabilitiesChanged";
    case EVREventType::VREvent_OverlayCreated:
        return "VREvent_OverlayCreated";
    case EVREventType::VREvent_OverlayDestroyed:
        return "VREvent_OverlayDestroyed";
    case EVREventType::VREvent_Notification_Shown:
        return "VREvent_Notification_Shown";
    case EVREventType::VREvent_Notification_Hidden:
        return "VREvent_Notification_Hidden";
    case EVREventType::VREvent_Notification_BeginInteraction:
        return "VREvent_Notification_BeginInteraction";
    case EVREventType::VREvent_Notification_Destroyed:
        return "VREvent_Notification_Destroyed";
    case EVREventType::VREvent_Quit:
        return "VREvent_Quit";
    case EVREventType::VREvent_ProcessQuit:
        return "VREvent_ProcessQuit";
    case EVREventType::VREvent_QuitAcknowledged:
        return "VREvent_QuitAcknowledged";
    case EVREventType::VREvent_DriverRequestedQuit:
        return "VREvent_DriverRequestedQuit";
    case EVREventType::VREvent_RestartRequested:
        return "VREvent_RestartRequested";
    case EVREventType::VREvent_InvalidateSwapTextureSets:
        return "VREvent_InvalidateSwapTextureSets";
    case EVREventType::VREvent_ChaperoneDataHasChanged:
        return "VREvent_ChaperoneDataHasChanged";
    case EVREventType::VREvent_ChaperoneUniverseHasChanged:
        return "VREvent_ChaperoneUniverseHasChanged";
    case EVREventType::VREvent_ChaperoneTempDataHasChanged:
        return "VREvent_ChaperoneTempDataHasChanged";
    case EVREventType::VREvent_ChaperoneSettingsHaveChanged:
        return "VREvent_ChaperoneSettingsHaveChanged";
    case EVREventType::VREvent_SeatedZeroPoseReset:
        return "VREvent_SeatedZeroPoseReset";
    case EVREventType::VREvent_ChaperoneFlushCache:
        return "VREvent_ChaperoneFlushCache";
    case EVREventType::VREvent_ChaperoneRoomSetupStarting:
        return "VREvent_ChaperoneRoomSetupStarting";
    case EVREventType::VREvent_StandingZeroPoseReset:
        return "VREvent_StandingZeroPoseReset";
    case EVREventType::VREvent_AudioSettingsHaveChanged:
        return "VREvent_AudioSettingsHaveChanged";
    case EVREventType::VREvent_BackgroundSettingHasChanged:
        return "VREvent_BackgroundSettingHasChanged";
    case EVREventType::VREvent_CameraSettingsHaveChanged:
        return "VREvent_CameraSettingsHaveChanged";
    case EVREventType::VREvent_ReprojectionSettingHasChanged:
        return "VREvent_ReprojectionSettingHasChanged";
    case EVREventType::VREvent_ModelSkinSettingsHaveChanged:
        return "VREvent_ModelSkinSettingsHaveChanged";
    case EVREventType::VREvent_EnvironmentSettingsHaveChanged:
        return "VREvent_EnvironmentSettingsHaveChanged";
    case EVREventType::VREvent_PowerSettingsHaveChanged:
        return "VREvent_PowerSettingsHaveChanged";
    case EVREventType::VREvent_EnableHomeAppSettingsHaveChanged:
        return "VREvent_EnableHomeAppSettingsHaveChanged";
    case EVREventType::VREvent_SteamVRSectionSettingChanged:
        return "VREvent_SteamVRSectionSettingChanged";
    case EVREventType::VREvent_LighthouseSectionSettingChanged:
        return "VREvent_LighthouseSectionSettingChanged";
    case EVREventType::VREvent_NullSectionSettingChanged:
        return "VREvent_NullSectionSettingChanged";
    case EVREventType::VREvent_UserInterfaceSectionSettingChanged:
        return "VREvent_UserInterfaceSectionSettingChanged";
    case EVREventType::VREvent_NotificationsSectionSettingChanged:
        return "VREvent_NotificationsSectionSettingChanged";
    case EVREventType::VREvent_KeyboardSectionSettingChanged:
        return "VREvent_KeyboardSectionSettingChanged";
    case EVREventType::VREvent_PerfSectionSettingChanged:
        return "VREvent_PerfSectionSettingChanged";
    case EVREventType::VREvent_DashboardSectionSettingChanged:
        return "VREvent_DashboardSectionSettingChanged";
    case EVREventType::VREvent_WebInterfaceSectionSettingChanged:
        return "VREvent_WebInterfaceSectionSettingChanged";
    case EVREventType::VREvent_TrackersSectionSettingChanged:
        return "VREvent_TrackersSectionSettingChanged";
    case EVREventType::VREvent_LastKnownSectionSettingChanged:
        return "VREvent_LastKnownSectionSettingChanged";
    case EVREventType::VREvent_DismissedWarningsSectionSettingChanged:
        return "VREvent_DismissedWarningsSectionSettingChanged";
    case EVREventType::VREvent_GpuSpeedSectionSettingChanged:
        return "VREvent_GpuSpeedSectionSettingChanged";
    case EVREventType::VREvent_WindowsMRSectionSettingChanged:
        return "VREvent_WindowsMRSectionSettingChanged";
    case EVREventType::VREvent_OtherSectionSettingChanged:
        return "VREvent_OtherSectionSettingChanged";
    case EVREventType::VREvent_AnyDriverSettingsChanged:
        return "VREvent_AnyDriverSettingsChanged";
    case EVREventType::VREvent_StatusUpdate:
        return "VREvent_StatusUpdate";
    case EVREventType::VREvent_WebInterface_InstallDriverCompleted:
        return "VREvent_WebInterface_InstallDriverCompleted";
    case EVREventType::VREvent_MCImageUpdated:
        return "VREvent_MCImageUpdated";
    case EVREventType::VREvent_FirmwareUpdateStarted:
        return "VREvent_FirmwareUpdateStarted";
    case EVREventType::VREvent_FirmwareUpdateFinished:
        return "VREvent_FirmwareUpdateFinished";
    case EVREventType::VREvent_KeyboardClosed:
        return "VREvent_KeyboardClosed";
    case EVREventType::VREvent_KeyboardCharInput:
        return "VREvent_KeyboardCharInput";
    case EVREventType::VREvent_KeyboardDone:
        return "VREvent_KeyboardDone";
    case EVREventType::VREvent_KeyboardOpened_Global:
        return "VREvent_KeyboardOpened_Global";
    case EVREventType::VREvent_KeyboardClosed_Global:
        return "VREvent_KeyboardClosed_Global";
    case EVREventType::VREvent_ApplicationListUpdated:
        return "VREvent_ApplicationListUpdated";
    case EVREventType::VREvent_ApplicationMimeTypeLoad:
        return "VREvent_ApplicationMimeTypeLoad";
    case EVREventType::VREvent_ProcessConnected:
        return "VREvent_ProcessConnected";
    case EVREventType::VREvent_ProcessDisconnected:
        return "VREvent_ProcessDisconnected";
    case EVREventType::VREvent_Compositor_ChaperoneBoundsShown:
        return "VREvent_Compositor_ChaperoneBoundsShown";
    case EVREventType::VREvent_Compositor_ChaperoneBoundsHidden:
        return "VREvent_Compositor_ChaperoneBoundsHidden";
    case EVREventType::VREvent_Compositor_DisplayDisconnected:
        return "VREvent_Compositor_DisplayDisconnected";
    case EVREventType::VREvent_Compositor_DisplayReconnected:
        return "VREvent_Compositor_DisplayReconnected";
    case EVREventType::VREvent_Compositor_HDCPError:
        return "VREvent_Compositor_HDCPError";
    case EVREventType::VREvent_Compositor_ApplicationNotResponding:
        return "VREvent_Compositor_ApplicationNotResponding";
    case EVREventType::VREvent_Compositor_ApplicationResumed:
        return "VREvent_Compositor_ApplicationResumed";
    case EVREventType::VREvent_Compositor_OutOfVideoMemory:
        return "VREvent_Compositor_OutOfVideoMemory";
    case EVREventType::VREvent_Compositor_DisplayModeNotSupported:
        return "VREvent_Compositor_DisplayModeNotSupported";
    case EVREventType::VREvent_Compositor_StageOverrideReady:
        return "VREvent_Compositor_StageOverrideReady";
    case EVREventType::VREvent_Compositor_RequestDisconnectReconnect:
        return "VREvent_Compositor_RequestDisconnectReconnect";
    case EVREventType::VREvent_TrackedCamera_StartVideoStream:
        return "VREvent_TrackedCamera_StartVideoStream";
    case EVREventType::VREvent_TrackedCamera_StopVideoStream:
        return "VREvent_TrackedCamera_StopVideoStream";
    case EVREventType::VREvent_TrackedCamera_PauseVideoStream:
        return "VREvent_TrackedCamera_PauseVideoStream";
    case EVREventType::VREvent_TrackedCamera_ResumeVideoStream:
        return "VREvent_TrackedCamera_ResumeVideoStream";
    case EVREventType::VREvent_TrackedCamera_EditingSurface:
        return "VREvent_TrackedCamera_EditingSurface";
    case EVREventType::VREvent_PerformanceTest_EnableCapture:
        return "VREvent_PerformanceTest_EnableCapture";
    case EVREventType::VREvent_PerformanceTest_DisableCapture:
        return "VREvent_PerformanceTest_DisableCapture";
    case EVREventType::VREvent_PerformanceTest_FidelityLevel:
        return "VREvent_PerformanceTest_FidelityLevel";
    case EVREventType::VREvent_MessageOverlay_Closed:
        return "VREvent_MessageOverlay_Closed";
    case EVREventType::VREvent_MessageOverlayCloseRequested:
        return "VREvent_MessageOverlayCloseRequested";
    case EVREventType::VREvent_Input_HapticVibration:
        return "VREvent_Input_HapticVibration";
    case EVREventType::VREvent_Input_BindingLoadFailed:
        return "VREvent_Input_BindingLoadFailed";
    case EVREventType::VREvent_Input_BindingLoadSuccessful:
        return "VREvent_Input_BindingLoadSuccessful";
    case EVREventType::VREvent_Input_ActionManifestReloaded:
        return "VREvent_Input_ActionManifestReloaded";
    case EVREventType::VREvent_Input_ActionManifestLoadFailed:
        return "VREvent_Input_ActionManifestLoadFailed";
    case EVREventType::VREvent_Input_ProgressUpdate:
        return "VREvent_Input_ProgressUpdate";
    case EVREventType::VREvent_Input_TrackerActivated:
        return "VREvent_Input_TrackerActivated";
    case EVREventType::VREvent_Input_BindingsUpdated:
        return "VREvent_Input_BindingsUpdated";
    case EVREventType::VREvent_Input_BindingSubscriptionChanged:
        return "VREvent_Input_BindingSubscriptionChanged";
    case EVREventType::VREvent_SpatialAnchors_PoseUpdated:
        return "VREvent_SpatialAnchors_PoseUpdated";
    case EVREventType::VREvent_SpatialAnchors_DescriptorUpdated:
        return "VREvent_SpatialAnchors_DescriptorUpdated";
    case EVREventType::VREvent_SpatialAnchors_RequestPoseUpdate:
        return "VREvent_SpatialAnchors_RequestPoseUpdate";
    case EVREventType::VREvent_SpatialAnchors_RequestDescriptorUpdate:
        return "VREvent_SpatialAnchors_RequestDescriptorUpdate";
    case EVREventType::VREvent_SystemReport_Started:
        return "VREvent_SystemReport_Started";
    case EVREventType::VREvent_Monitor_ShowHeadsetView:
        return "VREvent_Monitor_ShowHeadsetView";
    case EVREventType::VREvent_Monitor_HideHeadsetView:
        return "VREvent_Monitor_HideHeadsetView";
    case EVREventType::VREvent_Audio_SetSpeakersVolume:
        return "VREvent_Audio_SetSpeakersVolume";
    case EVREventType::VREvent_Audio_SetSpeakersMute:
        return "VREvent_Audio_SetSpeakersMute";
    case EVREventType::VREvent_Audio_SetMicrophoneVolume:
        return "VREvent_Audio_SetMicrophoneVolume";
    case EVREventType::VREvent_Audio_SetMicrophoneMute:
        return "VREvent_Audio_SetMicrophoneMute";
    case EVREventType::VREvent_VendorSpecific_Reserved_Start:
        return "VREvent_VendorSpecific_Reserved_Start";
    case EVREventType::VREvent_VendorSpecific_Reserved_End:
        return "VREvent_VendorSpecific_Reserved_End";

    default:
        return fmt::format("VREvent_{}", (uint32_t)eventType);
    }
}
}

std::string format_as(VkResult vkResult)
{
    switch (vkResult) {
    case VK_SUCCESS:
        return "VK_SUCCESS";
    case VK_NOT_READY:
        return "VK_NOT_READY";
    case VK_TIMEOUT:
        return "VK_TIMEOUT";
    case VK_EVENT_SET:
        return "VK_EVENT_SET";
    case VK_EVENT_RESET:
        return "VK_EVENT_RESET";
    case VK_INCOMPLETE:
        return "VK_INCOMPLETE";
    case VK_ERROR_OUT_OF_HOST_MEMORY:
        return "VK_ERROR_OUT_OF_HOST_MEMORY";
    case VK_ERROR_OUT_OF_DEVICE_MEMORY:
        return "VK_ERROR_OUT_OF_DEVICE_MEMORY";
    case VK_ERROR_INITIALIZATION_FAILED:
        return "VK_ERROR_INITIALIZATION_FAILED";
    case VK_ERROR_DEVICE_LOST:
        return "VK_ERROR_DEVICE_LOST";
    case VK_ERROR_MEMORY_MAP_FAILED:
        return "VK_ERROR_MEMORY_MAP_FAILED";
    case VK_ERROR_LAYER_NOT_PRESENT:
        return "VK_ERROR_LAYER_NOT_PRESENT";
    case VK_ERROR_EXTENSION_NOT_PRESENT:
        return "VK_ERROR_EXTENSION_NOT_PRESENT";
    case VK_ERROR_FEATURE_NOT_PRESENT:
        return "VK_ERROR_FEATURE_NOT_PRESENT";
    case VK_ERROR_INCOMPATIBLE_DRIVER:
        return "VK_ERROR_INCOMPATIBLE_DRIVER";
    case VK_ERROR_TOO_MANY_OBJECTS:
        return "VK_ERROR_TOO_MANY_OBJECTS";
    case VK_ERROR_FORMAT_NOT_SUPPORTED:
        return "VK_ERROR_FORMAT_NOT_SUPPORTED";
    case VK_ERROR_FRAGMENTED_POOL:
        return "VK_ERROR_FRAGMENTED_POOL";
    case VK_ERROR_UNKNOWN:
        return "VK_ERROR_UNKNOWN";
    case VK_ERROR_VALIDATION_FAILED:
        return "VK_ERROR_VALIDATION_FAILED";
    case VK_ERROR_OUT_OF_POOL_MEMORY:
        return "VK_ERROR_OUT_OF_POOL_MEMORY";
    case VK_ERROR_INVALID_EXTERNAL_HANDLE:
        return "VK_ERROR_INVALID_EXTERNAL_HANDLE";
    case VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS:
        return "VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS";
    case VK_ERROR_FRAGMENTATION:
        return "VK_ERROR_FRAGMENTATION";
    case VK_PIPELINE_COMPILE_REQUIRED:
        return "VK_PIPELINE_COMPILE_REQUIRED";
    case VK_ERROR_NOT_PERMITTED:
        return "VK_ERROR_NOT_PERMITTED";
    case VK_ERROR_SURFACE_LOST_KHR:
        return "VK_ERROR_SURFACE_LOST_KHR";
    case VK_ERROR_NATIVE_WINDOW_IN_USE_KHR:
        return "VK_ERROR_NATIVE_WINDOW_IN_USE_KHR";
    case VK_SUBOPTIMAL_KHR:
        return "VK_SUBOPTIMAL_KHR";
    case VK_ERROR_OUT_OF_DATE_KHR:
        return "VK_ERROR_OUT_OF_DATE_KHR";
    case VK_ERROR_INCOMPATIBLE_DISPLAY_KHR:
        return "VK_ERROR_INCOMPATIBLE_DISPLAY_KHR";
    case VK_ERROR_INVALID_SHADER_NV:
        return "VK_ERROR_INVALID_SHADER_NV";
    case VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR:
        return "VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR";
    case VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR";
    case VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR";
    case VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR";
    case VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR";
    case VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR";
    case VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT:
        return "VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT";
    case VK_ERROR_PRESENT_TIMING_QUEUE_FULL_EXT:
        return "VK_ERROR_PRESENT_TIMING_QUEUE_FULL_EXT";
    case VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT:
        return "VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT";
    case VK_THREAD_IDLE_KHR:
        return "VK_THREAD_IDLE_KHR";
    case VK_THREAD_DONE_KHR:
        return "VK_THREAD_DONE_KHR";
    case VK_OPERATION_DEFERRED_KHR:
        return "VK_OPERATION_DEFERRED_KHR";
    case VK_OPERATION_NOT_DEFERRED_KHR:
        return "VK_OPERATION_NOT_DEFERRED_KHR";
    case VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR:
        return "VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR";
    case VK_ERROR_COMPRESSION_EXHAUSTED_EXT:
        return "VK_ERROR_COMPRESSION_EXHAUSTED_EXT";
    case VK_INCOMPATIBLE_SHADER_BINARY_EXT:
        return "VK_INCOMPATIBLE_SHADER_BINARY_EXT";
    case VK_PIPELINE_BINARY_MISSING_KHR:
        return "VK_PIPELINE_BINARY_MISSING_KHR";
    case VK_ERROR_NOT_ENOUGH_SPACE_KHR:
        return "VK_ERROR_NOT_ENOUGH_SPACE_KHR";
    case VK_RESULT_MAX_ENUM:
        return "VK_RESULT_MAX_ENUM";
    default:
        return fmt::format("VkResult_{}", (uint32_t)vkResult);
    }
}